// constants.ts
import type { Plant, Recipe, CommunityEvent } from './types';

export const DEFAULT_RECIPE_IMAGE_B64 = 'data:image/gif;base64,R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs=';

// --- PLANTS ---
// A comprehensive list of 150+ plants focusing on Indian and subtropical gardening.
export const PLANT_CATALOG: Plant[] = [
    // --- Vegetables (Solanaceae Family - Nightshades) ---
    { id: 1, name: 'Tomato (Roma)', icon: '🍅', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Dec', 'Jan', 'Feb', 'Mar'] },
    { id: 7, name: 'Chilli (Cayenne)', icon: '🌶️', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Jan', 'Feb', 'Mar', 'Apr'] },
    { id: 101, name: 'Capsicum (Bell Pepper)', icon: '🫑', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Dec', 'Jan', 'Feb', 'Mar'] },
    { id: 102, name: 'Brinjal (Eggplant)', icon: '🍆', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Jan', 'Feb', 'Mar', 'Apr'] },
    { id: 103, name: 'Potato', icon: '🥔', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['Mar', 'Apr', 'May'] },
    { id: 10, name: 'Chilli (Bhut Jolokia)', icon: '🌶️', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Feb', 'Mar', 'Apr'] },
    { id: 11, name: 'Tomato (Cherry)', icon: '🍅', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Nov', 'Dec', 'Jan', 'Feb'] },
    { id: 12, name: 'Chilli (Guntur)', icon: '🌶️', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Jan', 'Feb', 'Mar'] },
    { id: 13, name: 'Green Chilli', icon: '🌶️', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Jan', 'Feb', 'Mar', 'Apr', 'May'] },

    // --- Vegetables (Cucurbits - Gourds & Melons) ---
    { id: 3, name: 'Cucumber', icon: '🥒', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Dec', 'Jan', 'Feb'] },
    { id: 5, name: 'Zucchini (Courgette)', icon: '🥒', category: 'Vegetable', phenology: 'Flowering', fruitingMonths: ['Dec', 'Jan', 'Feb'] },
    { id: 14, name: 'Lauki (Bottle Gourd)', icon: '🍈', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Nov', 'Dec', 'Jan'] },
    { id: 15, name: 'Karela (Bitter Gourd)', icon: '🥒', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Dec', 'Jan', 'Feb'] },
    { id: 16, name: 'Turai (Ridge Gourd)', icon: '🥒', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Jan', 'Feb', 'Mar'] },
    { id: 17, name: 'Kaddu (Pumpkin)', icon: '🎃', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Apr', 'May', 'Jun'] },
    { id: 18, name: 'Watermelon', icon: '🍉', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Jan', 'Feb'] },
    { id: 19, name: 'Ash Gourd (Petha)', icon: '🍈', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Mar', 'Apr'] },
    { id: 20, name: 'Pointed Gourd (Parwal)', icon: '🥒', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Feb', 'Mar'] },
    { id: 21, name: 'Snake Gourd (Chichinda)', icon: '🥒', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Feb', 'Mar', 'Apr'] },
    { id: 22, name: 'Tinda (Indian Squash)', icon: '🍈', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Dec', 'Jan'] },

    // --- Vegetables (Legumes) ---
    { id: 23, name: 'Green Beans (French)', icon: '🫛', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Oct', 'Nov', 'Dec', 'Jan', 'Feb'] },
    { id: 24, name: 'Guar (Cluster Beans)', icon: '🫛', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Nov', 'Dec'] },
    { id: 25, name: 'Sem (Broad Beans)', icon: '🫛', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Aug', 'Sep'] },
    { id: 26, name: 'Matar (Peas)', icon: '🫛', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Jun', 'Jul', 'Aug'] },
    { id: 27, name: 'Cowpea (Lobia)', icon: '🫛', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Oct', 'Nov'] },
    { id: 28, name: 'Pigeon Pea (Toor/Arhar)', icon: '🫛', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Dec', 'Jan'] },
    { id: 29, name: 'Chickpea (Chana)', icon: '🫛', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Feb', 'Mar'] },
    { id: 30, name: 'Mung Bean (Moong)', icon: '🫛', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Mar', 'Apr'] },

    // --- Vegetables (Leafy Greens) ---
    { id: 104, name: 'Palak (Spinach)', icon: '🌿', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['May', 'Jun', 'Jul', 'Aug'] },
    { id: 6, name: 'Dhania (Coriander Leaves)', icon: '🌿', category: 'Herb', phenology: 'Vegetative', fruitingMonths: ['Apr', 'May', 'Jun', 'Jul', 'Aug'] },
    { id: 31, name: 'Methi (Fenugreek Leaves)', icon: '🌿', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['May', 'Jun', 'Jul'] },
    { id: 32, name: 'Sarson (Mustard Greens)', icon: '🥬', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['Jun', 'Jul', 'Aug'] },
    { id: 33, name: 'Bathua (Chenopodium)', icon: '🌿', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['Jun', 'Jul'] },
    { id: 34, name: 'Chaulai (Amaranth Greens)', icon: '🥬', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['Nov', 'Dec'] },
    { id: 35, name: 'Gongura (Roselle Leaves)', icon: '🌿', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['Dec', 'Jan'] },
    { id: 36, name: 'Malabar Spinach', icon: '🥬', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['Nov', 'Dec', 'Jan'] },
    { id: 37, name: 'Lettuce', icon: '🥬', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'] },
    { id: 38, name: 'Cabbage', icon: '🥬', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['May', 'Jun', 'Jul', 'Aug'] },
    
    // --- Vegetables (Root & Tuber) ---
    { id: 107, name: 'Carrot', icon: '🥕', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['Mar', 'Apr', 'May', 'Jun', 'Jul'] },
    { id: 108, name: 'Beetroot', icon: '🔴', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['Mar', 'Apr', 'May', 'Jun'] },
    { id: 109, name: 'Radish (Mooli)', icon: '⚪', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['Apr', 'May', 'Jun'] },
    { id: 112, name: 'Onion', icon: '🧅', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['Jan', 'Feb', 'Mar'] },
    { id: 113, name: 'Garlic', icon: '🧄', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['Apr', 'May'] },
    { id: 39, name: 'Ginger', icon: '🫚', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['Jan', 'Feb'] },
    { id: 40, name: 'Turmeric (Haldi)', icon: '🫚', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['Jan', 'Feb'] },
    { id: 115, name: 'Sweet Potato', icon: '🍠', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['Feb', 'Mar', 'Apr'] },
    { id: 41, name: 'Arbi (Taro/Colocasia)', icon: '🥔', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['Oct', 'Nov'] },
    { id: 42, name: 'Yam (Jimikand)', icon: '🥔', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['Nov', 'Dec'] },
    { id: 43, name: 'Turnip (Shalgam)', icon: '⚪', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['May', 'Jun', 'Jul'] },
    { id: 44, name: 'Spring Onion', icon: '🧅', category: 'Vegetable', phenology: 'Vegetative', fruitingMonths: ['Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'] },

    // --- Vegetables (Other) ---
    { id: 45, name: 'Bhindi (Okra)', icon: '🌿', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Jan', 'Feb', 'Mar'] },
    { id: 110, name: 'Broccoli', icon: '🥦', category: 'Vegetable', phenology: 'Flowering', fruitingMonths: ['Jun', 'Jul', 'Aug', 'Sep'] },
    { id: 145, name: 'Cauliflower (Gobi)', icon: '🥦', category: 'Vegetable', phenology: 'Flowering', fruitingMonths: ['Jun', 'Jul', 'Aug'] },
    { id: 119, name: 'Corn (Bhutta)', icon: '🌽', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Nov', 'Dec', 'Jan'] },
    { id: 46, name: 'Drumstick (Moringa)', icon: '🌿', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Mar', 'Apr'] },
    { id: 47, name: 'Green Papaya', icon: '🍈', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] },
    { id: 48, name: 'Raw Banana', icon: '🍌', category: 'Vegetable', phenology: 'Fruiting', fruitingMonths: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] },

    // --- Fruits ---
    { id: 50, name: 'Aam (Mango)', icon: '🥭', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Nov', 'Dec', 'Jan'] },
    { id: 51, name: 'Kela (Banana)', icon: '🍌', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] },
    { id: 52, name: 'Amrood (Guava)', icon: '🍈', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Jul', 'Aug', 'Nov', 'Dec'] },
    { id: 53, name: 'Papita (Papaya)', icon: '🍈', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] },
    { id: 54, name: 'Anar (Pomegranate)', icon: '🔴', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Jan', 'Feb', 'Mar'] },
    { id: 55, name: 'Sitaphal (Custard Apple)', icon: '🍈', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Sep', 'Oct'] },
    { id: 56, name: 'Chikoo (Sapodilla)', icon: '🟤', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Jan', 'Feb', 'May', 'Jun'] },
    { id: 57, name: 'Nimbu (Lemon/Lime)', icon: '🍋', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Jun', 'Jul', 'Aug', 'Nov', 'Dec'] },
    { id: 58, name: 'Amla (Indian Gooseberry)', icon: '🟢', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Oct', 'Nov'] },
    { id: 59, name: 'Kathal (Jackfruit)', icon: '🍈', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Jun', 'Jul'] },
    { id: 60, name: 'Jamun (Java Plum)', icon: '🍇', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Jun', 'Jul'] },
    { id: 61, name: 'Ber (Indian Jujube)', icon: '🍎', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Oct', 'Nov'] },
    { id: 62, name: 'Karonda (Carandas Cherry)', icon: '🍒', category: 'Fruit', phenology: 'Fruiting', fruitingMonths: ['Jul', 'Aug'] },
    { id: 127, name: 'Passionfruit', icon: '🟤', category: 'Berry or Vine', phenology: 'Fruiting', fruitingMonths: ['Dec', 'Jan', 'Feb'] },
    { id: 129, name: 'Angoor (Grape)', icon: '🍇', category: 'Berry or Vine', phenology: 'Fruiting', fruitingMonths: ['Jan', 'Feb'] },
    { id: 126, name: 'Strawberry', icon: '🍓', category: 'Berry or Vine', phenology: 'Fruiting', fruitingMonths: ['Aug', 'Sep', 'Oct'] },
    
    // --- Herbs & Spices ---
    { id: 2, name: 'Tulsi (Holy Basil)', icon: '🌿', category: 'Herb', phenology: 'Vegetative', fruitingMonths: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] },
    { id: 4, name: 'Pudina (Mint)', icon: '🌿', category: 'Herb', phenology: 'Vegetative', fruitingMonths: ['Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr'] },
    { id: 70, name: 'Kadi Patta (Curry Leaves)', icon: '🌿', category: 'Herb', phenology: 'Vegetative', fruitingMonths: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] },
    { id: 71, name: 'Lemongrass', icon: '🌿', category: 'Herb', phenology: 'Vegetative', fruitingMonths: ['Oct', 'Nov', 'Dec', 'Jan'] },
    { id: 72, name: 'Ajwain (Carom)', icon: '🌿', category: 'Herb', phenology: 'Vegetative', fruitingMonths: ['May', 'Jun'] },
    { id: 73, name: 'Jeera (Cumin)', icon: '🌿', category: 'Herb', phenology: 'Flowering', fruitingMonths: ['Feb', 'Mar'] },
    { id: 74, name: 'Saunf (Fennel)', icon: '🌿', category: 'Herb', phenology: 'Flowering', fruitingMonths: ['Mar', 'Apr'] },
    { id: 75, name: 'Rai (Mustard)', icon: '🌼', category: 'Herb', phenology: 'Flowering', fruitingMonths: ['Jan', 'Feb'] },
    { id: 76, name: 'Elaichi (Cardamom)', icon: '🌿', category: 'Herb', phenology: 'Fruiting', fruitingMonths: ['Sep', 'Oct'] },
    { id: 77, name: 'Dalchini (Cinnamon)', icon: '🌿', category: 'Herb', phenology: 'Harvest', fruitingMonths: ['May', 'Nov'] },
    { id: 78, name: 'Laung (Clove)', icon: '🌿', category: 'Herb', phenology: 'Flowering', fruitingMonths: ['Jan', 'Feb'] },
    { id: 79, name: 'Tej Patta (Bay Leaf)', icon: '🌿', category: 'Herb', phenology: 'Vegetative', fruitingMonths: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] },
    { id: 80, name: 'Kalonji (Nigella Sativa)', icon: '🌿', category: 'Herb', phenology: 'Flowering', fruitingMonths: ['Mar', 'Apr'] },
    { id: 122, name: 'Rosemary', icon: '🌿', category: 'Herb', phenology: 'Vegetative', fruitingMonths: ['Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'] },
    { id: 123, name: 'Thyme', icon: '🌿', category: 'Herb', phenology: 'Vegetative', fruitingMonths: ['Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'] },
    { id: 124, name: 'Oregano', icon: '🌿', category: 'Herb', phenology: 'Vegetative', fruitingMonths: ['Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr'] },

    // --- Flowers (Edible & Companion) ---
    { id: 130, name: 'Genda (Marigold)', icon: '🌼', category: 'Flower', phenology: 'Flowering', fruitingMonths: ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'] },
    { id: 90, name: 'Gulab (Rose)', icon: '🌹', category: 'Flower', phenology: 'Flowering', fruitingMonths: ['Feb', 'Mar', 'Sep', 'Oct'] },
    { id: 91, name: 'Mogra (Jasmine Sambac)', icon: '💮', category: 'Flower', phenology: 'Flowering', fruitingMonths: ['Apr', 'May', 'Jun', 'Jul'] },
    { id: 92, name: 'Gudhal (Hibiscus)', icon: '🌺', category: 'Flower', phenology: 'Flowering', fruitingMonths: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] },
    { id: 131, name: 'Sunflower', icon: '🌻', category: 'Flower', phenology: 'Flowering', fruitingMonths: ['Nov', 'Dec', 'Jan'] },
    { id: 93, name: 'Aparajita (Butterfly Pea)', icon: '💙', category: 'Flower', phenology: 'Flowering', fruitingMonths: ['Aug', 'Sep', 'Oct'] },
    { id: 157, name: 'Chamomile', icon: '🌼', category: 'Flower', phenology: 'Flowering', fruitingMonths: ['Sep', 'Oct'] },
    { id: 94, name: 'Parijat (Night-flowering Jasmine)', icon: '🌸', category: 'Flower', phenology: 'Flowering', fruitingMonths: ['Sep', 'Oct'] },
];

export const INITIAL_GARDEN: Plant[] = PLANT_CATALOG.filter(p => [
    1, // Tomato
    7, // Chilli
    102, // Brinjal
    45, // Bhindi
    14, // Lauki
    104, // Palak
    6, // Dhania
    4, // Mint
    70, // Curry Leaves
    39, // Ginger
    112, // Onion
    113, // Garlic
].includes(p.id));

// --- RECIPES ---
// (Expanded and corrected)
export const RECIPE_CATALOG: Recipe[] = [
    {
        id: 'rcp_chana_masala',
        name: 'Chana Masala',
        image: '🍲',
        course: 'main',
        diet_tags: ['vegan', 'vegetarian', 'gluten-free'],
        spice_level: 2,
        prep_minutes: 15,
        cook_minutes: 30,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: true,
        high_protein: true,
        low_carb: false,
        gluten_free: true,
        protein_grams: 15,
        fiber_grams: 12,
        carbs_grams: 45,
        source: 'preloaded',
        keyIngredients: ['Tomato', 'Onion', 'Garlic', 'Chilli'],
        ingredients: "2 tbsp oil\n1 large onion, finely chopped\n2 cloves garlic, minced\n1 inch ginger, grated\n1 green chilli, slit\n2 large tomatoes, pureed\n1 tsp turmeric powder\n1 tsp red chilli powder\n1 tsp coriander powder\n1 tsp cumin powder\n1/2 tsp garam masala\n2 cans (400g each) chickpeas, rinsed\nSalt to taste\nFresh coriander for garnish",
        instructions: "1. Heat oil in a pan. Sauté onions until golden brown.\n2. Add garlic, ginger, and green chilli. Sauté for a minute.\n3. Add tomato puree and all the spice powders except garam masala. Cook until oil separates.\n4. Add the rinsed chickpeas and salt. Mix well.\n5. Add 1 cup of water, bring to a boil, then simmer for 15-20 minutes.\n6. Stir in garam masala. Garnish with fresh coriander and serve hot.",
        imageMetadata: { source: 'ai_generated', status: 'pending' }
    },
    {
        id: 'rcp_palak_dal',
        name: 'Palak Dal (Spinach Lentils)',
        image: '🥣',
        course: 'main',
        diet_tags: ['vegan', 'vegetarian', 'gluten-free'],
        spice_level: 1,
        prep_minutes: 10,
        cook_minutes: 25,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: true,
        high_protein: true,
        low_carb: false,
        gluten_free: true,
        protein_grams: 18,
        fiber_grams: 15,
        carbs_grams: 35,
        source: 'preloaded',
        keyIngredients: ['Spinach', 'Tomato', 'Onion', 'Garlic'],
        ingredients: "1 cup toor dal (pigeon peas), rinsed\n2 cups chopped spinach\n1 small onion, chopped\n1 small tomato, chopped\n1/2 tsp turmeric powder\nSalt to taste\nFor Tempering:\n1 tbsp ghee or oil\n1 tsp cumin seeds\n2 cloves garlic, minced\n2 dried red chillies",
        instructions: "1. In a pressure cooker, combine dal, spinach, onion, tomato, turmeric, salt, and 3 cups of water.\n2. Cook for 3-4 whistles or until dal is soft.\n3. Mash the dal lightly.\n4. For tempering, heat ghee/oil in a small pan. Add cumin seeds, minced garlic, and dried red chillies.\n5. Pour the tempering over the dal and mix well. Serve hot.",
        imageMetadata: { source: 'ai_generated', status: 'pending' }
    },
    {
        id: 'rcp_masoor_dal',
        name: 'Masoor Dal (Red Lentil Soup)',
        image: '🥣',
        course: 'soup',
        diet_tags: ['vegan', 'vegetarian', 'gluten-free'],
        spice_level: 1,
        prep_minutes: 5,
        cook_minutes: 20,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: true,
        high_protein: true,
        low_carb: false,
        gluten_free: true,
        protein_grams: 14,
        fiber_grams: 10,
        carbs_grams: 30,
        source: 'preloaded',
        keyIngredients: ['Onion', 'Tomato', 'Garlic'],
        ingredients: "1 cup masoor dal (red lentils), rinsed\n1/2 tsp turmeric powder\nSalt to taste\nFor Tempering:\n1 tbsp oil\n1 tsp mustard seeds\n1 tsp cumin seeds\n1 small onion, sliced\n1 small tomato, chopped\nCurry leaves",
        instructions: "1. Cook the rinsed masoor dal with turmeric, salt, and 3 cups of water until soft.\n2. In a separate pan, heat oil for tempering. Add mustard seeds and cumin seeds.\n3. Once they splutter, add onion and curry leaves. Sauté until onion is translucent.\n4. Add tomato and cook until soft.\n5. Pour this tempering over the cooked dal. Mix well and simmer for 5 minutes.",
        imageMetadata: { source: 'ai_generated', status: 'pending' }
    },
    {
        id: 'rcp_moong_dal_tadka',
        name: 'Moong Dal Tadka',
        image: '🥣',
        course: 'main',
        diet_tags: ['vegan', 'vegetarian', 'gluten-free'],
        spice_level: 1,
        prep_minutes: 10,
        cook_minutes: 20,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: true,
        high_protein: true,
        low_carb: false,
        gluten_free: true,
        protein_grams: 16,
        fiber_grams: 11,
        carbs_grams: 32,
        source: 'preloaded',
        keyIngredients: ['Tomato', 'Onion', 'Garlic', 'Coriander'],
        ingredients: "1 cup yellow moong dal, rinsed\n1/2 tsp turmeric powder\nSalt to taste\nFor Tadka:\n2 tbsp ghee or oil\n1 tsp cumin seeds\n1/2 tsp asafoetida (hing)\n1 medium onion, finely chopped\n1 medium tomato, finely chopped\n1 tsp ginger-garlic paste\n1/2 tsp red chilli powder\n1/2 tsp garam masala\nChopped coriander for garnish",
        instructions: "1. Pressure cook moong dal with turmeric, salt, and 3 cups of water for 2-3 whistles.\n2. Heat ghee/oil in a pan. Add cumin seeds and hing.\n3. Add onion and sauté until golden.\n4. Add ginger-garlic paste and sauté for a minute.\n5. Add tomato and cook until mushy. Add red chilli powder and garam masala.\n6. Pour the tadka over the cooked dal, mix well. Garnish with coriander.",
        imageMetadata: { source: 'ai_generated', status: 'pending' }
    },
    {
        id: 'rcp_bhindi_masala',
        name: 'Bhindi Masala (Okra Stir Fry)',
        image: '🥘',
        course: 'side',
        diet_tags: ['vegan', 'vegetarian', 'gluten-free'],
        spice_level: 2,
        prep_minutes: 15,
        cook_minutes: 20,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: true,
        high_protein: false,
        low_carb: true,
        gluten_free: true,
        protein_grams: 3,
        fiber_grams: 4,
        carbs_grams: 9,
        source: 'preloaded',
        keyIngredients: ['Okra', 'Onion', 'Tomato', 'Chilli'],
        ingredients: "500g okra (bhindi), washed and chopped\n1 large onion, sliced\n1 large tomato, chopped\n1 tsp cumin seeds\n1 tsp turmeric powder\n1 tsp red chilli powder\n1 tsp coriander powder\n1/2 tsp amchur (dry mango powder)\n2 tbsp oil\nSalt to taste",
        instructions: "1. Heat oil in a pan. Add cumin seeds.\n2. Add sliced onions and sauté until translucent.\n3. Add the chopped okra and sauté on medium-high heat for 5-7 minutes until it's no longer slimy.\n4. Add tomatoes and all the spice powders. Mix well.\n5. Cover and cook on low heat for 10-12 minutes, stirring occasionally, until the okra is tender.\n6. Uncover, add amchur powder, mix, and cook for another 2 minutes.",
        imageMetadata: { source: 'preloaded', status: 'cached' }
    },
    {
        id: 'rcp_baingan_bharta',
        name: 'Baingan Bharta (Smoky Eggplant Mash)',
        image: '🍆',
        course: 'main',
        diet_tags: ['vegan', 'vegetarian', 'gluten-free'],
        spice_level: 2,
        prep_minutes: 10,
        cook_minutes: 30,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: true,
        high_protein: false,
        low_carb: true,
        gluten_free: true,
        protein_grams: 2,
        fiber_grams: 5,
        carbs_grams: 10,
        source: 'preloaded',
        keyIngredients: ['Eggplant', 'Tomato', 'Onion', 'Garlic'],
        ingredients: "1 large eggplant (baingan)\n1 large onion, finely chopped\n2 medium tomatoes, finely chopped\n3-4 cloves garlic, minced\n1 inch ginger, grated\n1 green chilli, chopped\n1 tsp cumin seeds\n1/2 tsp turmeric powder\n1 tsp red chilli powder\n1 tsp coriander powder\n1/2 tsp garam masala\n3 tbsp oil\nSalt to taste\nCoriander for garnish",
        instructions: "1. Roast the eggplant directly over a flame or in the oven until the skin is charred and the flesh is soft. Let it cool.\n2. Peel the charred skin off the eggplant and mash the flesh.\n3. Heat oil in a pan. Add cumin seeds.\n4. Add onion and sauté until golden brown.\n5. Add ginger, garlic, and green chilli. Sauté for a minute.\n6. Add tomatoes and all spice powders except garam masala. Cook until oil separates.\n7. Add the mashed eggplant and salt. Mix well and cook for 10-15 minutes.\n8. Stir in garam masala and garnish with fresh coriander.",
        imageMetadata: { source: 'preloaded', status: 'cached' }
    },
     {
        id: 'rcp_rajma_masala',
        name: 'Rajma Masala (Low Oil)',
        image: '🍛',
        course: 'main',
        diet_tags: ['vegan', 'vegetarian', 'gluten-free'],
        spice_level: 2,
        prep_minutes: 15,
        cook_minutes: 45,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: true,
        high_protein: true,
        low_carb: false,
        gluten_free: true,
        protein_grams: 17,
        fiber_grams: 15,
        carbs_grams: 40,
        source: 'preloaded',
        keyIngredients: ['Tomato', 'Onion', 'Garlic'],
        ingredients: "1 cup kidney beans (rajma), soaked overnight\n1 large onion, pureed\n2 large tomatoes, pureed\n1 tsp ginger-garlic paste\n1 green chilli\n1 tsp turmeric powder\n1 tsp red chilli powder\n1.5 tsp coriander powder\n1 tsp cumin powder\n1 tsp garam masala\n1 tbsp oil\nSalt to taste",
        instructions: "1. Pressure cook soaked rajma with salt and enough water for 5-6 whistles or until tender.\n2. In a pan, heat oil. Add onion puree and cook until it turns brown.\n3. Add ginger-garlic paste and green chilli. Sauté for a minute.\n4. Add tomato puree and all spice powders except garam masala. Cook until oil separates.\n5. Add the cooked rajma along with its water. Mash a few beans to thicken the gravy.\n6. Simmer for 15-20 minutes. Add garam masala. Serve hot.",
        imageMetadata: { source: 'ai_generated', status: 'pending' }
    },
    {
        id: 'rcp_sambar',
        name: 'Sambar (Low Oil)',
        image: '🍲',
        course: 'soup',
        diet_tags: ['vegan', 'vegetarian', 'gluten-free'],
        spice_level: 2,
        prep_minutes: 20,
        cook_minutes: 30,
        servings: 6,
        diabetic_friendly: true,
        high_fiber: true,
        high_protein: true,
        low_carb: false,
        gluten_free: true,
        protein_grams: 10,
        fiber_grams: 8,
        carbs_grams: 25,
        source: 'preloaded',
        keyIngredients: ['Tomato', 'Onion', 'Carrot', 'Eggplant'],
        ingredients: "1 cup toor dal\n1 cup mixed vegetables (carrots, beans, pumpkin, eggplant)\n1 small onion, chopped\n1 large tomato, chopped\nSmall piece of tamarind, soaked in water\n2 tbsp sambar powder\n1/2 tsp turmeric powder\nSalt to taste\nFor Tempering:\n1 tsp oil\n1 tsp mustard seeds\n2 dried red chillies\nA pinch of asafoetida (hing)\nCurry leaves",
        instructions: "1. Pressure cook toor dal with turmeric and water until mushy.\n2. In a separate pot, cook the mixed vegetables with onion, tomato, and some water until tender.\n3. Add the cooked dal to the vegetables. Add tamarind extract, sambar powder, and salt. \n4. Bring to a boil and simmer for 10-15 minutes.\n5. Prepare tempering by heating oil and adding mustard seeds, red chillies, asafoetida, and curry leaves.\n6. Pour the tempering over the sambar and serve hot.",
        imageMetadata: { source: 'ai_generated', status: 'pending' }
    },
    {
        id: 'rcp_lemon_rice',
        name: 'Lemon Rice',
        image: '🍋',
        course: 'side',
        diet_tags: ['vegan', 'vegetarian', 'gluten-free'],
        spice_level: 1,
        prep_minutes: 5,
        cook_minutes: 15,
        servings: 2,
        diabetic_friendly: false,
        high_fiber: false,
        high_protein: false,
        low_carb: false,
        gluten_free: true,
        protein_grams: 4,
        fiber_grams: 2,
        carbs_grams: 45,
        source: 'preloaded',
        keyIngredients: ['Chilli', 'Coriander'],
        ingredients: "2 cups cooked rice\n2 tbsp lemon juice\nFor Tempering:\n2 tbsp oil\n1 tsp mustard seeds\n1 tsp chana dal\n1 tbsp peanuts or cashews\n2 dried red chillies\n1 green chilli, slit\nCurry leaves\n1/2 tsp turmeric powder\nA pinch of asafoetida (hing)\nSalt to taste",
        instructions: "1. Fluff the cooked rice and let it cool slightly.\n2. Heat oil in a pan. Add mustard seeds, chana dal, and peanuts. Sauté until golden.\n3. Add red chillies, green chilli, and curry leaves. Sauté for a few seconds.\n4. Add turmeric powder and asafoetida. Mix.\n5. Add the cooked rice and salt. Mix gently but thoroughly.\n6. Turn off the heat. Add lemon juice and mix well. Garnish with coriander if desired.",
        imageMetadata: { source: 'preloaded', status: 'cached' }
    },
    {
        id: 'rcp_turmeric_milk',
        name: 'Golden Milk (Turmeric Latte)',
        image: '🥛',
        course: 'beverage',
        diet_tags: ['vegetarian', 'gluten-free'],
        spice_level: 0,
        prep_minutes: 2,
        cook_minutes: 5,
        servings: 1,
        diabetic_friendly: true,
        high_fiber: false,
        high_protein: false,
        low_carb: true,
        gluten_free: true,
        protein_grams: 8,
        fiber_grams: 1,
        carbs_grams: 10,
        source: 'preloaded',
        keyIngredients: [],
        ingredients: "1 cup milk of your choice\n1/2 tsp turmeric powder\n1/4 tsp ground ginger\nA pinch of black pepper\n1/2 tsp cinnamon powder\n1 tsp honey or maple syrup (optional)",
        instructions: "1. In a small saucepan, whisk together milk, turmeric, ginger, pepper, and cinnamon.\n2. Heat over medium heat until warm but not boiling.\n3. Remove from heat and stir in sweetener if using.\n4. Pour into a mug and enjoy.",
        imageMetadata: { source: 'preloaded', status: 'cached' }
    },
    {
        id: 'rcp_masala_chai_low_sugar',
        name: 'Masala Chai (Low Sugar)',
        image: '☕',
        course: 'beverage',
        diet_tags: ['vegetarian', 'gluten-free'],
        spice_level: 0,
        prep_minutes: 2,
        cook_minutes: 10,
        servings: 2,
        diabetic_friendly: true,
        high_fiber: false,
        high_protein: false,
        low_carb: true,
        gluten_free: true,
        protein_grams: 4,
        fiber_grams: 0,
        carbs_grams: 5,
        source: 'preloaded',
        keyIngredients: [],
        ingredients: "1 cup water\n1 inch ginger, crushed\n2-3 cardamom pods, crushed\n1 small cinnamon stick\n2 cloves\n1 cup milk\n2 tsp black tea leaves\nSweetener to taste (e.g., stevia, or very little sugar)",
        instructions: "1. In a saucepan, bring water to a boil with ginger, cardamom, cinnamon, and cloves.\n2. Simmer for 5 minutes to infuse the spices.\n3. Add the tea leaves and simmer for 2 more minutes.\n4. Add milk and bring to a gentle boil.\n5. Strain the chai into cups. Add sweetener if desired and serve hot.",
        imageMetadata: { source: 'preloaded', status: 'cached' }
    },
    {
        id: 'rcp_bruschetta',
        name: 'Tomato & Basil Bruschetta',
        image: '🥖',
        course: 'snack',
        diet_tags: ['vegetarian'],
        spice_level: 0,
        prep_minutes: 15,
        cook_minutes: 5,
        servings: 4,
        diabetic_friendly: false,
        high_fiber: false,
        high_protein: false,
        low_carb: false,
        gluten_free: false,
        protein_grams: 5,
        fiber_grams: 2,
        carbs_grams: 25,
        source: 'preloaded',
        keyIngredients: ['Tomato', 'Basil', 'Garlic'],
        ingredients: "4 large ripe tomatoes, diced\n1/2 cup fresh basil leaves, chopped\n2 cloves garlic, minced\n1 tbsp balsamic vinegar\n2 tbsp olive oil\nSalt and pepper to taste\n1 baguette, sliced",
        instructions: "1. In a bowl, combine diced tomatoes, chopped basil, minced garlic, balsamic vinegar, and olive oil.\n2. Season with salt and pepper. Let it sit for at least 10 minutes for the flavors to meld.\n3. Toast the baguette slices until golden and crisp.\n4. Rub one side of each toast with a whole garlic clove (optional).\n5. Top each slice of toast with the tomato mixture just before serving.",
        imageMetadata: { source: 'ai_generated', status: 'pending' }
    }
];

export const INITIAL_COOKBOOK: Recipe[] = RECIPE_CATALOG.filter(r => [
    'rcp_chana_masala', 
    'rcp_palak_dal',
    'rcp_bhindi_masala',
    'rcp_baingan_bharta',
].includes(r.id));

// --- COMMUNITY EVENTS ---
export const COMMUNITY_EVENTS: CommunityEvent[] = [
    {
        id: 1,
        name: 'Logan Community Garden - Monthly Meetup',
        date: 'First Saturday of every month, 9 AM',
        location: '123 Garden Lane, Logan Central',
        description: 'Join fellow gardeners to share tips, swap seeds, and work on our community plots. All skill levels welcome!',
    },
    {
        id: 2,
        name: 'Subtropical Fruit Tree Grafting Workshop',
        date: 'Sunday, August 25th, 2024, 10 AM - 1 PM',
        location: 'Logan West Library Community Hall',
        description: 'Learn the art of grafting from master gardener John Doe. Bring your own rootstock or purchase on the day. Limited spots available.',
    },
    {
        id: 3,
        name: 'Organic Pest Control for Beginners',
        date: 'Saturday, September 14th, 2024, 11 AM',
        location: 'Kingston Butter Factory Cultural Precinct',
        description: 'A free seminar on identifying and managing common garden pests using organic, bee-friendly methods.',
    },
];