// constants.ts

import type { Plant, Recipe, CommunityEvent } from './types';

export const PLANT_CATALOG: Plant[] = [
    // Australia & New Zealand
    { id: 101, name: "Aniseed Myrtle", icon: "🌿", category: "Herb", phenology: "Vegetative", fruitingMonths: [] },
    { id: 102, name: "Atherton Raspberry", icon: "🍇", category: "Berry or Vine", phenology: "Fruiting", fruitingMonths: ["Dec", "Jan", "Feb"] },
    { id: 103, name: "Bunya Nut", icon: "🌰", category: "Fruit", phenology: "Harvest", fruitingMonths: ["Jan", "Feb", "Mar"] },
    { id: 104, name: "Burdekin Plum", icon: "🍑", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Dec", "Jan", "Feb"] },
    { id: 105, name: "Candle Nut", icon: "🌰", category: "Fruit", phenology: "Harvest", fruitingMonths: ["Apr", "May", "Jun"] },
    { id: 106, name: "Cinnamon Myrtle", icon: "🌿", category: "Herb", phenology: "Vegetative", fruitingMonths: [] },
    { id: 107, name: "Davidson's Plum", icon: "🍑", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Dec", "Jan", "Feb"] },
    { id: 108, name: "Native Yam (Ipomoea costata)", icon: "🍠", category: "Vegetable", phenology: "Harvest", fruitingMonths: ["May", "Jun", "Jul"] },
    { id: 109, name: "Large Leaf Native Tamarind", icon: "🌳", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Mar", "Apr", "May"] },
    { id: 110, name: "Lemon Myrtle", icon: "🍋", category: "Herb", phenology: "Vegetative", fruitingMonths: [] },
    { id: 111, name: "Lilly Pilly", icon: "🍒", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Dec", "Jan", "Feb"] },
    { id: 112, name: "Macadamia Nut", icon: "🌰", category: "Fruit", phenology: "Harvest", fruitingMonths: ["Mar", "Apr", "May"] },
    { id: 113, name: "Small Leaved Native Tamarind", icon: "🌳", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Mar", "Apr", "May"] },
    { id: 114, name: "Peanut Tree", icon: "🌳", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Apr", "May"] },
    { id: 115, name: "Sandpaper Fig", icon: "🌳", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Jan", "Feb", "Mar"] },
    { id: 116, name: "Warrigal Green", icon: "🥬", category: "Vegetable", phenology: "Vegetative", fruitingMonths: [] },
    { id: 117, name: "LEMONADE", icon: "🍋", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["May", "Jun", "Jul"] },
    { id: 118, name: "Oca Yam", icon: "🍠", category: "Vegetable", phenology: "Harvest", fruitingMonths: ["May", "Jun"] },

    // South American
    { id: 201, name: "ABIU", icon: "🟡", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Jan", "Feb", "Mar"] },
    { id: 202, name: "ACHACHA", icon: "🟠", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Dec", "Jan", "Feb"] },
    { id: 203, name: "ACHIOTE", icon: "🌶️", category: "Herb", phenology: "Fruiting", fruitingMonths: ["Mar", "Apr", "May"] },
    { id: 204, name: "Amaranth", icon: "🥬", category: "Vegetable", phenology: "Vegetative", fruitingMonths: [] },
    { id: 205, name: "ARROWROOT", icon: "🍠", category: "Vegetable", phenology: "Harvest", fruitingMonths: ["Jun", "Jul", "Aug"] },
    { id: 206, name: "BRAZILIAN CHERRY", icon: "🍒", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Oct", "Nov", "Dec"] },
    { id: 207, name: "Canistel", icon: "💛", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Dec", "Jan", "Feb"] },
    { id: 208, name: "CASSAVA", icon: "🍠", category: "Vegetable", phenology: "Harvest", fruitingMonths: ["May", "Jun", "Jul"] },
    { id: 209, name: "Cherry Guava", icon: "🍒", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Mar", "Apr"] },
    { id: 210, name: "CHERIMOYA", icon: "💚", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Jul", "Aug", "Sep"] },
    { id: 211, name: "CHERRY RIO GRANDE", icon: "🍒", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Sep", "Oct"] },
    { id: 212, name: "FEIJOA", icon: "🍐", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Apr", "May"] },
    { id: 213, name: "GRUMICHAMA", icon: "⚫", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Oct", "Nov"] },
    { id: 214, name: "GUAVA", icon: "🍈", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Feb", "Mar", "Apr"] },
    { id: 215, name: "ICE-CREAM BEAN", icon: "🍦", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Jan", "Feb", "Mar"] },
    { id: 216, name: "JABOTICABA", icon: "🍇", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Sep", "Oct", "Mar", "Apr"] },
    { id: 217, name: "Jack Bean", icon: "🌱", category: "Vegetable", phenology: "Fruiting", fruitingMonths: ["Nov", "Dec", "Jan"] },
    { id: 218, name: "Malabar Chestnut", icon: "🌰", category: "Fruit", phenology: "Harvest", fruitingMonths: ["Mar", "Apr"] },
    { id: 219, name: "Madagascar Beans", icon: "🌱", category: "Vegetable", phenology: "Fruiting", fruitingMonths: ["Dec", "Jan", "Feb"] },
    { id: 220, name: "Passionfruit", icon: "💜", category: "Berry or Vine", phenology: "Fruiting", fruitingMonths: ["Dec", "Jan", "Feb"] },
    { id: 221, name: "Pumpkin", icon: "🎃", category: "Vegetable", phenology: "Fruiting", fruitingMonths: ["Mar", "Apr", "May"] },
    { id: 222, name: "Rollina", icon: "🟡", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Feb", "Mar", "Apr"] },

    // North America, Mexico & Caribbean
    { id: 301, name: "ACEROLA CHERRY", icon: "🍒", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Oct", "Nov", "Dec"] },
    { id: 302, name: "ALLSPICE", icon: "🌿", category: "Herb", phenology: "Fruiting", fruitingMonths: ["Jul", "Aug"] },
    { id: 303, name: "AVOCADO", icon: "🥑", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Jul", "Aug", "Sep"] },
    { id: 304, name: "BLACK SAPOTE", icon: "🍫", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Jun", "Jul", "Aug"] },
    { id: 305, name: "Bush passionfruit", icon: "💜", category: "Berry or Vine", phenology: "Fruiting", fruitingMonths: ["Dec", "Jan", "Feb"] },
    { id: 306, name: "CAPULIN CHERRY", icon: "🍒", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Nov", "Dec"] },
    { id: 307, name: "CHILLI", icon: "🌶️", category: "Vegetable", phenology: "Fruiting", fruitingMonths: ["Jan", "Feb", "Mar"] },
    { id: 308, name: "GUIANA CHESTNUT", icon: "🌰", category: "Fruit", phenology: "Harvest", fruitingMonths: ["Mar", "Apr"] },
    { id: 309, name: "GRAPEFRUIT", icon: "🍊", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Jun", "Jul", "Aug"] },
    { id: 310, name: "HAZELNUT", icon: "🌰", category: "Fruit", phenology: "Harvest", fruitingMonths: ["Aug", "Sep"] },
    { id: 311, name: "Mountain Soursop", icon: "💚", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Aug", "Sep", "Oct"] },
    { id: 312, name: "Muscadine Grape", icon: "🍇", category: "Berry or Vine", phenology: "Fruiting", fruitingMonths: ["Feb", "Mar"] },
    { id: 313, name: "Pecan Nut", icon: "🌰", category: "Fruit", phenology: "Harvest", fruitingMonths: ["Apr", "May"] },
    { id: 314, name: "Sapodila", icon: "🍮", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Feb", "Mar", "Apr"] },
    { id: 315, name: "Sea Grape", icon: "🍇", category: "Berry or Vine", phenology: "Fruiting", fruitingMonths: ["Mar", "Apr"] },
    { id: 316, name: "Star Apple", icon: "⭐", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Feb", "Mar", "Apr"] },
    { id: 317, name: "White Sapote", icon: "⚪", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Apr", "May", "Jun"] },

    // Asia and Indian Subcontinent
    { id: 401, name: "Almond", icon: "🌰", category: "Fruit", phenology: "Harvest", fruitingMonths: ["Feb", "Mar"] },
    { id: 402, name: "AMBARELLA", icon: "🍈", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["May", "Jun"] },
    { id: 403, name: "AMLA", icon: "🟢", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Apr", "May"] },
    { id: 404, name: "Banana", icon: "🍌", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] },
    { id: 405, name: "Betel Piper", icon: "🌿", category: "Herb", phenology: "Vegetative", fruitingMonths: [] },
    { id: 406, name: "Black BAMBOO", icon: "🎋", category: "Vegetable", phenology: "Vegetative", fruitingMonths: [] },
    { id: 407, name: "Brahmi", icon: "🌿", category: "Herb", phenology: "Vegetative", fruitingMonths: [] },
    { id: 408, name: "Bronze loquat", icon: "🍑", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Sep", "Oct"] },
    { id: 409, name: "CARAMBOLA", icon: "⭐", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Apr", "May", "Sep", "Oct"] },
    { id: 410, name: "CARDAMON", icon: "🌿", category: "Herb", phenology: "Fruiting", fruitingMonths: ["Sep", "Oct", "Nov"] },
    { id: 411, name: "CINNAMON", icon: "🌿", category: "Herb", phenology: "Harvest", fruitingMonths: [] },
    { id: 412, name: "CITRON", icon: "🍋", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Jun", "Jul", "Aug"] },
    { id: 413, name: "CURRY LEAF", icon: "🌿", category: "Herb", phenology: "Vegetative", fruitingMonths: [] },
    { id: 414, name: "Eggplant", icon: "🍆", category: "Vegetable", phenology: "Fruiting", fruitingMonths: ["Dec", "Jan", "Feb"] },
    { id: 415, name: "GALANGAL", icon: "🍠", category: "Herb", phenology: "Harvest", fruitingMonths: ["May", "Jun"] },
    { id: 416, name: "GINGER", icon: "🍠", category: "Herb", phenology: "Harvest", fruitingMonths: ["May", "Jun"] },
    { id: 417, "name": "Gotu Kola", "icon": "🍀", "category": "Herb", "phenology": "Vegetative", fruitingMonths: [] },
    { id: 418, name: "Hong Kong kumquat", icon: "🍊", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Jun", "Jul"] },
    { id: 419, name: "HORSERADISH TREE", icon: "🌳", category: "Vegetable", phenology: "Fruiting", fruitingMonths: ["Apr", "May", "Jun"] },
    { id: 420, name: "Indian Long Pepper", icon: "🌶️", category: "Herb", phenology: "Fruiting", fruitingMonths: ["Jan", "Feb"] },
    { id: 421, name: "Ivy gourd", icon: "🥒", category: "Vegetable", phenology: "Fruiting", fruitingMonths: ["Nov", "Dec", "Jan"] },
    { id: 422, name: "JAKFRUIT", icon: "🍈", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Jun", "Jul", "Aug"] },
    { id: 423, name: "Jambolan Plum", icon: "🍇", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["May", "Jun"] },
    { id: 424, name: "Kencur aromatic ginger", icon: "🍠", category: "Herb", phenology: "Harvest", fruitingMonths: ["May", "Jun"] },
    { id: 425, name: "Lablab Bean", icon: "🌱", category: "Vegetable", phenology: "Fruiting", fruitingMonths: ["May", "Jun"] },
    { id: 426, name: "LEMON", icon: "🍋", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Apr", "May", "Jun"] },
    { id: 427, name: "Lotus", icon: "🌸", category: "Vegetable", phenology: "Harvest", fruitingMonths: ["Jul", "Aug", "Sep"] },
    { id: 428, name: "LEMON GRASS", icon: "🌿", category: "Herb", phenology: "Vegetative", fruitingMonths: [] },
    { id: 429, name: "Jujube", icon: "🍎", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Feb", "Mar"] },
    { id: 430, name: "LIME", icon: "🍈", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Mar", "Apr", "May"] },
    { id: 431, name: "LONGAN", icon: "🍑", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Feb", "Mar"] },
    { id: 432, name: "LOQUAT", icon: "🍑", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Sep", "Oct"] },
    { id: 433, name: "LYCHEE", icon: "🍒", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Dec", "Jan"] },
    { id: 434, name: "MANDARIN", icon: "🍊", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Jun", "Jul"] },
    { id: 435, name: "Mango", icon: "🥭", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Dec", "Jan", "Feb"] },
    { id: 436, name: "Mangosteen", icon: "💜", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Dec", "Jan", "Feb"] },
    { id: 437, name: "Mango Ginger", icon: "🍠", category: "Herb", phenology: "Harvest", fruitingMonths: ["Apr", "May"] },
    { id: 438, name: "Myoga ginger", icon: "🌸", category: "Herb", phenology: "Flowering", fruitingMonths: [] },
    { id: 439, name: "Neem Tree", icon: "🌳", category: "Herb", phenology: "Vegetative", fruitingMonths: [] },
    { id: 440, name: "Orange", icon: "🍊", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Jul", "Aug", "Sep"] },
    { id: 441, name: "Pandanus", icon: "🌿", category: "Herb", phenology: "Vegetative", fruitingMonths: [] },
    { id: 442, name: "Pepper", icon: "⚫", category: "Herb", phenology: "Fruiting", fruitingMonths: ["Dec", "Jan"] },
    { id: 443, name: "Pigeon Pea", icon: "🌱", category: "Vegetable", phenology: "Fruiting", fruitingMonths: ["May", "Jun"] },
    { id: 444, name: "Pumelo", icon: "🍈", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Jul", "Aug", "Sep"] },
    { id: 445, name: "Rose Apple", icon: "🍎", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Nov", "Dec"] },
    { id: 446, name: "Santol", icon: "🟡", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Jul", "Aug"] },
    { id: 447, name: "Snake beans", icon: "🌱", category: "Vegetable", phenology: "Fruiting", fruitingMonths: ["Nov", "Dec", "Jan"] },
    { id: 448, name: "Snake Gourd", icon: "🐍", category: "Vegetable", phenology: "Fruiting", fruitingMonths: ["Dec", "Jan", "Feb"] },
    { id: 449, name: "Taro", icon: "🍠", category: "Vegetable", phenology: "Harvest", fruitingMonths: ["Jun", "Jul", "Aug"] },
    { id: 450, name: "Tea", icon: "🍵", category: "Herb", phenology: "Vegetative", fruitingMonths: [] },
    { id: 451, name: "Turmeric", icon: "🍠", category: "Herb", phenology: "Harvest", fruitingMonths: ["Apr", "May"] },
    { id: 452, name: "Vetiver Grass", icon: "🌿", category: "Herb", phenology: "Vegetative", fruitingMonths: [] },
    { id: 453, name: "Wampee", icon: "🟡", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Jun", "Jul"] },
    { id: 454, name: "Wax Gourd", icon: "🍈", category: "Vegetable", phenology: "Fruiting", fruitingMonths: ["Mar", "Apr", "May"] },
    { id: 455, name: "Wax Jambu", icon: "🔔", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Nov", "Dec"] },

    // Middle East and Africa
    { id: 501, name: "African mangosteen", icon: "🟠", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Dec", "Jan"] },
    { id: 502, name: "ALOE VERA", icon: "🌿", category: "Herb", phenology: "Vegetative", fruitingMonths: [] },
    { id: 503, name: "APPLE", icon: "🍎", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Feb", "Mar", "Apr"] },
    { id: 504, name: "Bottle Gourd", icon: "🍈", category: "Vegetable", phenology: "Fruiting", fruitingMonths: ["Dec", "Jan", "Feb"] },
    { id: 505, name: "CAROB TREE", icon: "🌳", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Aug", "Sep"] },
    { id: 506, name: "COFFEE", icon: "☕", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Jun", "Jul"] },
    { id: 507, name: "DATE", icon: "🌴", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Mar", "Apr"] },
    { id: 508, name: "Miracle Fruit", icon: "🍓", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["May", "Jun", "Jul"] },
    { id: 509, name: "Natal Plum", icon: "🍓", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Dec", "Jan", "Feb"] },
    { id: 510, name: "New Guinea Bean", icon: "🍈", category: "Vegetable", phenology: "Fruiting", fruitingMonths: ["Jan", "Feb", "Mar"] },
    { id: 511, name: "Olive", icon: "🫒", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Apr", "May", "Jun"] },
    { id: 512, name: "Okra", icon: "🌱", category: "Vegetable", phenology: "Fruiting", fruitingMonths: ["Nov", "Dec", "Jan"] },
    { id: 513, name: "Pomegranate", icon: "🔴", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Mar", "Apr", "May"] },
    { id: 514, name: "Rosella", icon: "🌺", category: "Flower", phenology: "Fruiting", fruitingMonths: ["Apr", "May"] },
    { id: 515, name: "Walnut", icon: "🌰", category: "Fruit", phenology: "Harvest", fruitingMonths: ["Mar", "Apr"] },
    { id: 516, name: "WATERMELON", icon: "🍉", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Dec", "Jan", "Feb"] },

    // Mediterranean and Europe
    { id: 601, name: "BAY TREE", icon: "🌿", category: "Herb", phenology: "Vegetative", fruitingMonths: [] },
    { id: 602, name: "FIG", icon: "💜", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Feb", "Mar", "Apr"] },
    { id: 603, name: "Pear", icon: "🍐", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Feb", "Mar"] },
    { id: 604, name: "Quince", icon: "💛", category: "Fruit", phenology: "Fruiting", fruitingMonths: ["Mar", "Apr"] },
    
    // Palms & Ornamentals (categorized as flowers for simplicity)
    { id: 701, name: "Foxtail Palm", icon: "🌴", category: "Flower", phenology: "Vegetative", fruitingMonths: [] },
    { id: 702, name: "Kentia Palm", icon: "🌴", category: "Flower", phenology: "Vegetative", fruitingMonths: [] },
    { id: 703, name: "Solitary Palm", icon: "🌴", category: "Flower", phenology: "Vegetative", fruitingMonths: [] },
    { id: 704, name: "Walking-stick Palm", icon: "🌴", category: "Flower", phenology: "Vegetative", fruitingMonths: [] },
    { id: 705, name: "Black Boy", icon: "🌳", category: "Flower", phenology: "Flowering", fruitingMonths: [] },
];

export const RECIPE_CATALOG: Recipe[] = [
    {
        id: 'rcp_chana_masala',
        name: 'Chana Masala',
        image: 'https://images.unsplash.com/photo-1631452180519-c084195d046b?q=80&w=2070&auto=format&fit=crop',
        course: 'main',
        diet_tags: ['vegetarian', 'diabetic_friendly', 'high_fiber'],
        spice_level: 2,
        prep_minutes: 10,
        cook_minutes: 30,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: true,
        high_protein: false,
        low_carb: false,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Chickpeas', 'Tomato'],
        ingredients: '1 cup chickpeas, soaked\n2 onions, finely chopped\n2 tomatoes, pureed\n1 tsp ginger-garlic paste\nSpices: turmeric, chili powder, coriander powder, chana masala powder\nOil, salt',
        instructions: '1. Cook chickpeas until soft.\n2. Sauté onions, ginger-garlic paste.\n3. Add tomato puree and spices, cook until oil separates.\n4. Add chickpeas, simmer for 15 mins.'
    },
    {
        id: 'rcp_palak_dal',
        name: 'Palak Dal',
        image: 'https://images.unsplash.com/photo-1609361369335-a2a225358055?q=80&w=1974&auto=format&fit=crop',
        course: 'main',
        diet_tags: ['vegetarian', 'diabetic_friendly', 'high_protein'],
        spice_level: 1,
        prep_minutes: 10,
        cook_minutes: 25,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: false,
        high_protein: true,
        low_carb: false,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Spinach', 'Lentils'],
        ingredients: '1 cup toor dal\n2 cups spinach, chopped\n1 onion, chopped\n1 tomato, chopped\nSpices: turmeric, cumin seeds, mustard seeds\nOil, salt, garlic',
        instructions: '1. Pressure cook dal until soft.\n2. Sauté spices, onion, garlic, tomato.\n3. Add spinach and cook until wilted.\n4. Mix with cooked dal and simmer.'
    },
    {
        id: 'rcp_masoor_dal',
        name: 'Masoor Dal',
        image: 'https://images.unsplash.com/photo-1585237630263-3662214c2275?q=80&w=2070&auto=format&fit=crop',
        course: 'main',
        diet_tags: ['vegetarian', 'diabetic_friendly', 'high_protein'],
        spice_level: 1,
        prep_minutes: 5,
        cook_minutes: 20,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: false,
        high_protein: true,
        low_carb: false,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Lentils'],
        ingredients: '1 cup masoor dal\n1 onion, chopped\n1 tomato, chopped\nSpices: turmeric, cumin seeds, chili powder\nOil, salt, cilantro',
        instructions: '1. Cook masoor dal until mushy.\n2. Prepare tadka with spices, onion, tomato.\n3. Pour tadka over dal, garnish with cilantro.'
    },
    {
        id: 'rcp_moong_dal_tadka',
        name: 'Moong Dal Tadka',
        image: 'https://images.unsplash.com/photo-1604928141068-a2d04573d635?q=80&w=2070&auto=format&fit=crop',
        course: 'main',
        diet_tags: ['vegetarian', 'diabetic_friendly', 'high_protein'],
        spice_level: 1,
        prep_minutes: 10,
        cook_minutes: 20,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: false,
        high_protein: true,
        low_carb: false,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Moong Dal'],
        ingredients: '1 cup moong dal\n1 onion, chopped\n1 tomato, chopped\nSpices: cumin seeds, mustard seeds, turmeric\nOil, ghee, salt, asafoetida',
        instructions: '1. Cook moong dal until soft and creamy.\n2. Prepare tadka with ghee, spices, onion, and tomato.\n3. Pour the sizzling tadka over the dal and stir.'
    },
    {
        id: 'rcp_rajma_masala_low_oil',
        name: 'Rajma Masala (Low Oil)',
        image: 'https://images.unsplash.com/photo-1565557623262-b27e252489a4?q=80&w=1970&auto=format&fit=crop',
        course: 'main',
        diet_tags: ['vegetarian', 'diabetic_friendly', 'high_fiber'],
        spice_level: 2,
        prep_minutes: 15,
        cook_minutes: 30,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: true,
        high_protein: false,
        low_carb: false,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Kidney Beans', 'Tomato'],
        ingredients: '1 cup kidney beans, soaked and boiled\n2 onions, pureed\n3 tomatoes, pureed\n1 tsp ginger-garlic paste\nSpices: rajma masala, turmeric, chili powder\nCilantro for garnish',
        instructions: '1. Sauté onion puree until golden.\n2. Add ginger-garlic paste, then tomato puree and spices. Cook until fragrant.\n3. Add boiled rajma and simmer for 20 minutes.'
    },
    {
        id: 'rcp_sambar_low_oil',
        name: 'Sambar (Low Oil)',
        image: 'https://images.unsplash.com/photo-1606464871404-e7045b3469b2?q=80&w=1974&auto=format&fit=crop',
        course: 'main',
        diet_tags: ['vegetarian', 'diabetic_friendly', 'high_fiber'],
        spice_level: 2,
        prep_minutes: 15,
        cook_minutes: 30,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: true,
        high_protein: false,
        low_carb: false,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Lentils', 'Tamarind'],
        ingredients: '1 cup toor dal\n1 cup mixed vegetables (drumstick, pumpkin, carrots)\nTamarind pulp\nSambar powder\nSpices: mustard seeds, curry leaves, asafoetida',
        instructions: '1. Cook dal and vegetables together until soft.\n2. Add tamarind pulp and sambar powder. Simmer for 10 minutes.\n3. Prepare a tadka with spices and pour over the sambar.'
    },
    {
        id: 'rcp_baingan_bharta',
        name: 'Baingan Bharta',
        image: 'https://plus.unsplash.com/premium_photo-1669680785643-e5559a8e2621?q=80&w=2070&auto=format&fit=crop',
        course: 'main',
        diet_tags: ['vegetarian', 'diabetic_friendly', 'low_carb'],
        spice_level: 2,
        prep_minutes: 15,
        cook_minutes: 30,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: false,
        high_protein: false,
        low_carb: true,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Eggplant', 'Tomato'],
        ingredients: '1 large eggplant\n2 onions, finely chopped\n2 tomatoes, finely chopped\nGreen chilies, ginger, garlic\nSpices: turmeric, chili powder, garam masala',
        instructions: '1. Roast the eggplant over an open flame until the skin is charred and the flesh is soft.\n2. Peel, mash the eggplant, and set aside.\n3. Sauté onions, ginger, garlic, and chilies. Add tomatoes and spices. Cook until soft.\n4. Add the mashed eggplant and cook for 10 minutes.'
    },
    {
        id: 'rcp_bhindi_masala',
        name: 'Bhindi Masala',
        image: 'https://plus.unsplash.com/premium_photo-1669680785163-952431a47341?q=80&w=2070&auto=format&fit=crop',
        course: 'side',
        diet_tags: ['vegetarian', 'diabetic_friendly', 'low_carb'],
        spice_level: 2,
        prep_minutes: 10,
        cook_minutes: 20,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: false,
        high_protein: false,
        low_carb: true,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Okra', 'Tomato'],
        ingredients: '250g okra, chopped\n1 large onion, sliced\n2 tomatoes, chopped\nSpices: turmeric, chili powder, coriander powder, amchur (dried mango powder)\nOil, salt',
        instructions: '1. Sauté okra in a little oil until lightly browned and not slimy. Set aside.\n2. In the same pan, sauté onions until golden.\n3. Add tomatoes and spices, cook until soft and pulpy.\n4. Add back the cooked okra, mix well, and cook for 5 more minutes.'
    },
    {
        id: 'rcp_palak_paneer_low_fat',
        name: 'Palak Paneer (Low Fat)',
        image: 'https://images.unsplash.com/photo-1567337326463-343431695e1e?q=80&w=1974&auto=format&fit=crop',
        course: 'main',
        diet_tags: ['vegetarian', 'diabetic_friendly', 'high_protein'],
        spice_level: 1,
        prep_minutes: 15,
        cook_minutes: 20,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: false,
        high_protein: true,
        low_carb: false,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Spinach', 'Paneer'],
        ingredients: '200g low-fat paneer, cubed\n1 large bunch of spinach, blanched and pureed\n1 onion, finely chopped\n1 tomato, pureed\nSpices: cumin seeds, turmeric, garam masala',
        instructions: '1. Sauté onions until translucent. Add tomato puree and spices, cook.\n2. Add spinach puree and cook for 5 minutes.\n3. Add paneer cubes and simmer for another 5-7 minutes.'
    },
    {
        id: 'rcp_mixed_veg_curry',
        name: 'Mixed Veg Curry',
        image: 'https://images.unsplash.com/photo-1586959535027-2347a2a0752f?q=80&w=2070&auto=format&fit=crop',
        course: 'main',
        diet_tags: ['vegetarian', 'diabetic_friendly', 'high_fiber'],
        spice_level: 2,
        prep_minutes: 15,
        cook_minutes: 25,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: true,
        high_protein: false,
        low_carb: false,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Carrot', 'Beans', 'Cauliflower'],
        ingredients: '2 cups mixed vegetables (carrots, peas, beans, cauliflower)\n1 onion, chopped\n1 tomato, pureed\nSpices: turmeric, chili powder, garam masala\nOil, salt, ginger-garlic paste',
        instructions: '1. Sauté onion, ginger-garlic paste.\n2. Add tomato puree and spices, cook.\n3. Add vegetables, water, and simmer until cooked through.'
    },
    {
        id: 'rcp_methi_thepla',
        name: 'Methi Thepla',
        image: 'https://plus.unsplash.com/premium_photo-1669680785160-b1859132b53b?q=80&w=2070&auto=format&fit=crop',
        course: 'breakfast',
        diet_tags: ['vegetarian', 'diabetic_friendly', 'high_fiber'],
        spice_level: 1,
        prep_minutes: 15,
        cook_minutes: 20,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: true,
        high_protein: false,
        low_carb: false,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Fenugreek', 'Whole Wheat'],
        ingredients: '1 cup whole wheat flour\n1/2 cup chopped fenugreek leaves\nYogurt, turmeric, chili powder, salt\nOil for cooking',
        instructions: '1. Mix all ingredients to form a soft dough.\n2. Roll into thin circles and cook on a hot tawa with a little oil until golden brown spots appear.'
    },
    {
        id: 'rcp_moong_dal_cheela',
        name: 'Moong Dal Cheela',
        image: 'https://images.unsplash.com/photo-1626200244675-b52f7a951c3c?q=80&w=2070&auto=format&fit=crop',
        course: 'breakfast',
        diet_tags: ['vegetarian', 'diabetic_friendly', 'high_protein'],
        spice_level: 1,
        prep_minutes: 15,
        cook_minutes: 15,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: false,
        high_protein: true,
        low_carb: false,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Moong Dal'],
        ingredients: '1 cup yellow moong dal, soaked\nGinger, green chilies, salt, turmeric\nChopped vegetables like onion, tomato (optional)',
        instructions: '1. Grind soaked dal with ginger and chilies to a smooth batter.\n2. Add spices and vegetables.\n3. Pour batter onto a hot non-stick pan and cook on both sides until golden.'
    },
    {
        id: 'rcp_poha_low_oil',
        name: 'Poha (Low Oil)',
        image: 'https://images.unsplash.com/photo-1602936114820-b4a4a589b940?q=80&w=2070&auto=format&fit=crop',
        course: 'breakfast',
        diet_tags: ['vegetarian', 'diabetic_friendly'],
        spice_level: 1,
        prep_minutes: 10,
        cook_minutes: 15,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: false,
        high_protein: false,
        low_carb: false,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Flattened Rice', 'Peanuts'],
        ingredients: '1.5 cups thick poha (flattened rice)\n1 onion, chopped\nPeanuts, curry leaves, mustard seeds\nLemon juice, turmeric, salt, cilantro',
        instructions: '1. Rinse poha gently and let it soften.\n2. Sauté mustard seeds, curry leaves, peanuts, and onion.\n3. Add turmeric, then add the softened poha and salt. Mix gently.\n4. Garnish with lemon juice and cilantro.'
    },
    {
        id: 'rcp_jowar_roti',
        name: 'Jowar Roti',
        image: 'https://images.unsplash.com/photo-1599232463699-c063b036d653?q=80&w=2070&auto=format&fit=crop',
        course: 'main',
        diet_tags: ['vegetarian', 'diabetic_friendly', 'high_fiber', 'gluten_free'],
        spice_level: 0,
        prep_minutes: 10,
        cook_minutes: 15,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: true,
        high_protein: false,
        low_carb: false,
        gluten_free: true,
        source: 'preloaded',
        keyIngredients: ['Sorghum'],
        ingredients: '1 cup jowar (sorghum) flour\nWarm water\nSalt',
        instructions: '1. Knead the jowar flour with warm water and salt to make a smooth dough.\n2. Pat the dough into thin circles using your hands.\n3. Cook on a hot tawa and then puff it up on an open flame.'
    },
    {
        id: 'rcp_sprouts_salad',
        name: 'Sprouts Salad',
        image: 'https://images.unsplash.com/photo-1505253716362-afb74b62f848?q=80&w=2070&auto=format&fit=crop',
        course: 'snack',
        diet_tags: ['vegetarian', 'diabetic_friendly', 'high_protein', 'low_carb'],
        spice_level: 1,
        prep_minutes: 10,
        cook_minutes: 0,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: false,
        high_protein: true,
        low_carb: true,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Sprouts', 'Cucumber', 'Tomato'],
        ingredients: '2 cups mixed sprouts\n1 onion, chopped\n1 tomato, chopped\n1 cucumber, chopped\nLemon juice, chaat masala, salt',
        instructions: '1. Combine all ingredients in a large bowl.\n2. Toss well and serve immediately.'
    },
    {
        id: 'rcp_lemon_rice',
        name: 'Lemon Rice',
        image: 'https://plus.unsplash.com/premium_photo-1695276332114-e15862d46a6f?q=80&w=2070&auto=format&fit=crop',
        course: 'main',
        diet_tags: ['vegetarian', 'diabetic_friendly'],
        spice_level: 1,
        prep_minutes: 10,
        cook_minutes: 15,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: false,
        high_protein: false,
        low_carb: false,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Rice', 'Lemon'],
        ingredients: '2 cups cooked rice\n2 tbsp lemon juice\nSpices: mustard seeds, urad dal, chana dal, turmeric, dried red chilies\nPeanuts, curry leaves, oil, salt',
        instructions: '1. Heat oil, add spices and peanuts, sauté.\n2. Add turmeric and rice, mix well.\n3. Turn off heat, add lemon juice and salt, mix.'
    },
    {
        id: 'rcp_moong_dal_soup',
        name: 'Moong Dal Soup',
        image: 'https://images.unsplash.com/photo-1625603646822-00363983a54b?q=80&w=2070&auto=format&fit=crop',
        course: 'soup',
        diet_tags: ['vegetarian', 'diabetic_friendly', 'high_protein', 'low_carb'],
        spice_level: 1,
        prep_minutes: 10,
        cook_minutes: 20,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: false,
        high_protein: true,
        low_carb: true,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Moong Dal'],
        ingredients: '1/2 cup yellow moong dal\n4 cups water or vegetable broth\nTurmeric, salt, pepper\nGinger, grated\nLemon juice for garnish',
        instructions: '1. Pressure cook moong dal with turmeric and salt until very soft.\n2. Whisk the dal until smooth or lightly blend it.\n3. Add ginger and pepper, and simmer for 5 minutes.\n4. Garnish with a squeeze of lemon juice.'
    },
    {
        id: 'rcp_tomato_soup',
        name: 'Tomato Soup',
        image: 'https://images.unsplash.com/photo-1590347274213-5a0a3ad8a562?q=80&w=1974&auto=format&fit=crop',
        course: 'soup',
        diet_tags: ['vegetarian', 'diabetic_friendly', 'low_carb'],
        spice_level: 0,
        prep_minutes: 10,
        cook_minutes: 15,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: false,
        high_protein: false,
        low_carb: true,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Tomato', 'Basil'],
        ingredients: '4 large tomatoes, chopped\n1 small onion, chopped\n2 cloves garlic\n1 cup vegetable broth\nSalt, pepper, a pinch of sugar (optional), fresh basil',
        instructions: '1. Sauté onion and garlic.\n2. Add tomatoes and broth, simmer for 10 mins.\n3. Blend until smooth, season, and garnish with basil.'
    },
    {
        id: 'rcp_cucumber_raita',
        name: 'Cucumber Raita',
        image: 'https://images.unsplash.com/photo-1626084329596-8a421b47467b?q=80&w=1974&auto=format&fit=crop',
        course: 'side',
        diet_tags: ['vegetarian', 'diabetic_friendly', 'low_carb'],
        spice_level: 0,
        prep_minutes: 5,
        cook_minutes: 0,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: false,
        high_protein: false,
        low_carb: true,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Cucumber', 'Yogurt'],
        ingredients: '1 cup yogurt, whisked\n1/2 cup cucumber, grated\nRoasted cumin powder, salt, fresh cilantro',
        instructions: '1. Squeeze water from grated cucumber.\n2. Mix all ingredients in a bowl.\n3. Chill before serving.'
    },
    {
        id: 'rcp_coriander_chutney',
        name: 'Coriander Chutney',
        image: 'https://images.unsplash.com/photo-1598585429322-a92c81fb3a11?q=80&w=1974&auto=format&fit=crop',
        course: 'condiment',
        diet_tags: ['vegetarian', 'diabetic_friendly', 'low_carb', 'vegan'],
        spice_level: 2,
        prep_minutes: 10,
        cook_minutes: 0,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: false,
        high_protein: false,
        low_carb: true,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Coriander', 'Mint', 'Chilli'],
        ingredients: '2 cups fresh cilantro\n1 cup fresh mint\n1-2 green chilies\n1 inch ginger\nLemon juice, salt',
        instructions: '1. Blend all ingredients with a little water to a smooth paste.'
    },
    {
        id: 'rcp_turmeric_milk',
        name: 'Turmeric Milk',
        image: 'https://images.unsplash.com/photo-1566312239634-c0953a72629b?q=80&w=1974&auto=format&fit=crop',
        course: 'beverage',
        diet_tags: ['vegetarian', 'diabetic_friendly', 'anti_inflammatory'],
        spice_level: 0,
        prep_minutes: 5,
        cook_minutes: 10,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: false,
        high_protein: false,
        low_carb: false,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Turmeric', 'Milk'],
        ingredients: '1 cup milk (any kind)\n1/2 tsp turmeric powder\nA pinch of black pepper\nOptional: ginger, cinnamon, sweetener',
        instructions: '1. Gently heat all ingredients in a saucepan.\n2. Whisk well, do not boil.\n3. Pour into a mug and enjoy warm.'
    },
    {
        id: 'rcp_masala_chai_low_sugar',
        name: 'Masala Chai (Low Sugar)',
        image: 'https://images.unsplash.com/photo-1578899805437-4352b215281e?q=80&w=2070&auto=format&fit=crop',
        course: 'beverage',
        diet_tags: ['vegetarian', 'diabetic_friendly'],
        spice_level: 1,
        prep_minutes: 5,
        cook_minutes: 10,
        servings: 4,
        diabetic_friendly: true,
        high_fiber: false,
        high_protein: false,
        low_carb: false,
        gluten_free: false,
        source: 'preloaded',
        keyIngredients: ['Tea', 'Ginger', 'Cardamom'],
        ingredients: '1 cup water\n1 inch ginger, crushed\n2-3 cardamom pods, crushed\n1 cinnamon stick\n2 tsp black tea leaves\n1 cup milk\nSweetener to taste (optional)',
        instructions: '1. Boil water with spices for 5 minutes.\n2. Add tea leaves, simmer for 2 mins.\n3. Add milk, bring to a near boil.\n4. Strain and serve.'
    }
];

export const INITIAL_COOKBOOK: Recipe[] = [
    RECIPE_CATALOG[0],
    RECIPE_CATALOG[9],
    RECIPE_CATALOG[14]
];


export const COMMUNITY_EVENTS: CommunityEvent[] = [
    {
        id: 1,
        name: 'Logan Village Farmers Market',
        date: 'Every Sunday, 7am - 12pm',
        location: 'Logan Village Green',
        description: 'Find fresh local produce, artisan goods, and connect with fellow gardeners. A great place to trade tips and seeds!'
    },
    {
        id: 2,
        name: 'Community Garden Working Bee',
        date: 'First Saturday of each month, 9am - 11am',
        location: 'Kingston Butter Factory Community Garden',
        description: 'Join volunteers to help maintain our beautiful community garden. All skill levels welcome, tools provided.'
    },
    {
        id: 3,
        name: 'Subtropical Fruit Tree Pruning Workshop',
        date: 'Saturday, 28th October, 10am',
        location: 'Logan Central Library',
        description: 'Learn the best techniques for pruning mangoes, citrus, and other subtropical fruit trees for a healthy and productive harvest. Bookings essential.'
    }
];