// services/nutriServeFoodData.ts
import type { FoodGroup } from '../components/games/NutriServeTypes';
import * as visuals from '../components/games/nutriserve-ui/FoodVisuals';

/**
 * The central data source for all food items available in the NutriServe game.
 * - Nutrients are per 100g.
 * - Density is g/ml, crucial for converting volume to weight.
 * - Portion sizes are in grams.
 * - Volume options are in milliliters.
 */
export const FOOD_LIBRARY: FoodGroup[] = [
  {
    name: 'Grains',
    items: [
      {
        id: 'rice_white',
        label: 'White Rice',
        category: 'Grains',
        visual: visuals.RiceVisual,
        nutrients_per_100g: { calories_kcal: 130, protein_g: 2.7, carbs_g: 28, fiber_g: 0.4, fat_g: 0.3, sodium_mg: 1 },
        density_g_per_ml: 0.85,
        volume_options_ml: [80, 160, 240, 360],
        volume_labels: ['Small Katori', 'Scoop', 'Large Katori', 'Full Plate'],
      },
      {
        id: 'rice_brown',
        label: 'Brown Rice',
        category: 'Grains',
        visual: visuals.BrownRiceVisual,
        nutrients_per_100g: { calories_kcal: 111, protein_g: 2.6, carbs_g: 23, fiber_g: 1.8, fat_g: 0.9, sodium_mg: 5 },
        density_g_per_ml: 0.80,
        volume_options_ml: [80, 160, 240, 360],
        volume_labels: ['Small Katori', 'Scoop', 'Large Katori', 'Full Plate'],
      },
      {
        id: 'rice_red',
        label: 'Red Rice',
        category: 'Grains',
        visual: visuals.RedRiceVisual,
        nutrients_per_100g: { calories_kcal: 120, protein_g: 2.8, carbs_g: 26, fiber_g: 2.0, fat_g: 1.0, sodium_mg: 4 },
        density_g_per_ml: 0.82,
        volume_options_ml: [80, 160, 240],
        volume_labels: ['Small Katori', 'Scoop', 'Large Katori'],
      },
      {
        id: 'veg_biryani',
        label: 'Veg Biryani',
        category: 'Grains',
        visual: visuals.VegBiryaniVisual,
        nutrients_per_100g: { calories_kcal: 180, protein_g: 5, carbs_g: 30, fiber_g: 4, fat_g: 4, sodium_mg: 300 },
        density_g_per_ml: 0.85,
        volume_options_ml: [200, 300, 400],
        volume_labels: ['Small', 'Regular', 'Large'],
      },
      {
        id: 'lemon_rice',
        label: 'Lemon Rice',
        category: 'Grains',
        visual: visuals.LemonRiceVisual,
        nutrients_per_100g: { calories_kcal: 175, protein_g: 3, carbs_g: 35, fiber_g: 2, fat_g: 3, sodium_mg: 250 },
        density_g_per_ml: 0.85,
        volume_options_ml: [150, 250, 350],
        volume_labels: ['Small', 'Regular', 'Large'],
      },
    ],
  },
  {
    name: 'Lentils & Curries',
    items: [
      {
        id: 'chana_masala',
        label: 'Chana Masala',
        category: 'Lentils & Curries',
        visual: visuals.ChanaMasalaVisual,
        nutrients_per_100g: { calories_kcal: 135, protein_g: 7, carbs_g: 18, fiber_g: 7, fat_g: 4, sodium_mg: 250 },
        density_g_per_ml: 0.95,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'chickpea_curry',
        label: 'Chickpea Curry',
        category: 'Lentils & Curries',
        visual: visuals.CholeVisual, // Re-using Chole visual
        nutrients_per_100g: { calories_kcal: 140, protein_g: 6, carbs_g: 20, fiber_g: 6, fat_g: 4, sodium_mg: 280 },
        density_g_per_ml: 0.95,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'palak_dal',
        label: 'Palak Dal',
        category: 'Lentils & Curries',
        visual: visuals.PalakDalVisual,
        nutrients_per_100g: { calories_kcal: 110, protein_g: 6, carbs_g: 14, fiber_g: 5, fat_g: 3, sodium_mg: 200 },
        density_g_per_ml: 0.98,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'masoor_dal',
        label: 'Masoor Dal',
        category: 'Lentils & Curries',
        visual: visuals.MasoorDalVisual,
        nutrients_per_100g: { calories_kcal: 125, protein_g: 8, carbs_g: 19, fiber_g: 8, fat_g: 2, sodium_mg: 180 },
        density_g_per_ml: 0.98,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'moong_dal_tadka',
        label: 'Moong Dal Tadka',
        category: 'Lentils & Curries',
        visual: visuals.MoongDalTadkaVisual,
        nutrients_per_100g: { calories_kcal: 140, protein_g: 9, carbs_g: 17, fiber_g: 7, fat_g: 4, sodium_mg: 220 },
        density_g_per_ml: 0.98,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'rajma_masala',
        label: 'Rajma Masala',
        category: 'Lentils & Curries',
        visual: visuals.RajmaMasalaVisual,
        nutrients_per_100g: { calories_kcal: 145, protein_g: 8, carbs_g: 20, fiber_g: 8, fat_g: 4, sodium_mg: 280 },
        density_g_per_ml: 0.96,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'dal_tadka',
        label: 'Dal Tadka',
        category: 'Lentils & Curries',
        visual: visuals.DalVisual,
        nutrients_per_100g: { calories_kcal: 130, protein_g: 7, carbs_g: 16, fiber_g: 7, fat_g: 4, sodium_mg: 210 },
        density_g_per_ml: 0.98,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'paneer_butter_masala',
        label: 'Paneer Butter Masala',
        category: 'Lentils & Curries',
        visual: visuals.PaneerVisual,
        nutrients_per_100g: { calories_kcal: 240, protein_g: 10, carbs_g: 8, fiber_g: 2, fat_g: 18, sodium_mg: 450 },
        density_g_per_ml: 1.0,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
        isTreat: true,
      },
      {
        id: 'chicken_curry',
        label: 'Chicken Curry',
        category: 'Lentils & Curries',
        visual: visuals.ChickenCurryVisual,
        nutrients_per_100g: { calories_kcal: 190, protein_g: 18, carbs_g: 7, fiber_g: 2, fat_g: 10, sodium_mg: 380 },
        density_g_per_ml: 1.0,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'kerala_parippu_curry',
        label: 'Kerala Parippu Curry (Moong Dal)',
        category: 'Lentils & Curries',
        visual: visuals.KeralaParippuCurryVisual,
        nutrients_per_100g: { calories_kcal: 115, protein_g: 8, carbs_g: 15, fiber_g: 6, fat_g: 3, sodium_mg: 200 },
        density_g_per_ml: 0.98,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'kadala_curry',
        label: 'Kadala Curry (Brown Chickpea)',
        category: 'Lentils & Curries',
        visual: visuals.KadalaCurryVisual,
        nutrients_per_100g: { calories_kcal: 150, protein_g: 9, carbs_g: 22, fiber_g: 8, fat_g: 3, sodium_mg: 280 },
        density_g_per_ml: 0.96,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'mathi_sardine_curry',
        label: 'Mathi Kerala Sardine Curry',
        category: 'Lentils & Curries',
        visual: visuals.MathiSardineCurryVisual,
        nutrients_per_100g: { calories_kcal: 180, protein_g: 20, carbs_g: 5, fiber_g: 1, fat_g: 9, sodium_mg: 320 },
        density_g_per_ml: 1.0,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'kerala_lamb_curry',
        label: 'Keralan Lamb Curry',
        category: 'Lentils & Curries',
        visual: visuals.KeralaLambCurryVisual,
        nutrients_per_100g: { calories_kcal: 220, protein_g: 22, carbs_g: 6, fiber_g: 2, fat_g: 12, sodium_mg: 400 },
        density_g_per_ml: 1.0,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'kerala_beef_curry',
        label: 'Keralan Beef Curry',
        category: 'Lentils & Curries',
        visual: visuals.KeralaBeefCurryVisual,
        nutrients_per_100g: { calories_kcal: 240, protein_g: 24, carbs_g: 6, fiber_g: 2, fat_g: 14, sodium_mg: 420 },
        density_g_per_ml: 1.0,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
    ],
  },
  {
    name: 'Vegetable Dishes',
    items: [
      {
        id: 'baingan_bharta',
        label: 'Baingan Bharta',
        category: 'Vegetable Dishes',
        visual: visuals.BainganBhartaVisual,
        nutrients_per_100g: { calories_kcal: 80, protein_g: 2, carbs_g: 9, fiber_g: 4, fat_g: 4, sodium_mg: 150 },
        density_g_per_ml: 0.90,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'bhindi_masala',
        label: 'Bhindi Masala',
        category: 'Vegetable Dishes',
        visual: visuals.BhindiMasalaVisual,
        nutrients_per_100g: { calories_kcal: 95, protein_g: 2, carbs_g: 8, fiber_g: 3, fat_g: 6, sodium_mg: 180 },
        density_g_per_ml: 0.88,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'palak_paneer',
        label: 'Palak Paneer',
        category: 'Vegetable Dishes',
        visual: visuals.PalakPaneerVisual,
        nutrients_per_100g: { calories_kcal: 150, protein_g: 9, carbs_g: 7, fiber_g: 3, fat_g: 10, sodium_mg: 300 },
        density_g_per_ml: 0.95,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'mixed_veg_curry',
        label: 'Mixed Veg Curry',
        category: 'Vegetable Dishes',
        visual: visuals.MixedVegCurryVisual,
        nutrients_per_100g: { calories_kcal: 90, protein_g: 3, carbs_g: 10, fiber_g: 4, fat_g: 4, sodium_mg: 200 },
        density_g_per_ml: 0.92,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'aloo_gobi',
        label: 'Aloo Gobi',
        category: 'Vegetable Dishes',
        visual: visuals.AlooGobiVisual,
        nutrients_per_100g: { calories_kcal: 100, protein_g: 3, carbs_g: 12, fiber_g: 4, fat_g: 5, sodium_mg: 220 },
        density_g_per_ml: 0.85,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'beans_carrot_thoran',
        label: 'Beans & Carrot Thoran',
        category: 'Vegetable Dishes',
        visual: visuals.BeansCarrotThoranVisual,
        nutrients_per_100g: { calories_kcal: 75, protein_g: 2, carbs_g: 8, fiber_g: 4, fat_g: 3, sodium_mg: 150 },
        density_g_per_ml: 0.85,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'moringa_leaf_thoran',
        label: 'Moringa Leaf Thoran (Drumstick Leaves)',
        category: 'Vegetable Dishes',
        visual: visuals.MoringaLeafThoranVisual,
        nutrients_per_100g: { calories_kcal: 70, protein_g: 3, carbs_g: 7, fiber_g: 5, fat_g: 3, sodium_mg: 140 },
        density_g_per_ml: 0.80,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'banana_flower_thoran',
        label: 'Banana Flower Thoran',
        category: 'Vegetable Dishes',
        visual: visuals.BananaFlowerThoranVisual,
        nutrients_per_100g: { calories_kcal: 80, protein_g: 2, carbs_g: 9, fiber_g: 6, fat_g: 3, sodium_mg: 160 },
        density_g_per_ml: 0.85,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'jackfruit_seeds_thoran',
        label: 'Jackfruit Seeds Thoran (Chakkakuru)',
        category: 'Vegetable Dishes',
        visual: visuals.JackfruitSeedsThoranVisual,
        nutrients_per_100g: { calories_kcal: 135, protein_g: 5, carbs_g: 24, fiber_g: 4, fat_g: 2, sodium_mg: 180 },
        density_g_per_ml: 0.90,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'cabbage_thoran',
        label: 'Cabbage Thoran',
        category: 'Vegetable Dishes',
        visual: visuals.CabbageThoranVisual, // Assuming visual exists or mapping to generic
        nutrients_per_100g: { calories_kcal: 70, protein_g: 2, carbs_g: 8, fiber_g: 3, fat_g: 4, sodium_mg: 160 },
        density_g_per_ml: 0.85,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'beetroot_thoran',
        label: 'Beetroot Thoran',
        category: 'Vegetable Dishes',
        visual: visuals.BeetrootThoranVisual,
        nutrients_per_100g: { calories_kcal: 85, protein_g: 2, carbs_g: 12, fiber_g: 4, fat_g: 3, sodium_mg: 170 },
        density_g_per_ml: 0.90,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'snake_gourd_thoran',
        label: 'Snake Gourd Thoran (Padavalanga)',
        category: 'Vegetable Dishes',
        visual: visuals.SnakeGourdThoranVisual,
        nutrients_per_100g: { calories_kcal: 60, protein_g: 1, carbs_g: 6, fiber_g: 2, fat_g: 3, sodium_mg: 140 },
        density_g_per_ml: 0.80,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'bitter_gourd_pavakka',
        label: 'Bitter Gourd Fry (Pavakka)',
        category: 'Vegetable Dishes',
        visual: visuals.BitterGourdVisual,
        nutrients_per_100g: { calories_kcal: 110, protein_g: 3, carbs_g: 10, fiber_g: 3, fat_g: 7, sodium_mg: 200 },
        density_g_per_ml: 0.85,
        volume_options_ml: [80, 120, 160],
        volume_labels: ['Small', 'Standard', 'Large'],
      },
      {
        id: 'kovakka_fry',
        label: 'Ivy Gourd Fry (Kovakka)',
        category: 'Vegetable Dishes',
        visual: visuals.IvyGourdVisual,
        nutrients_per_100g: { calories_kcal: 95, protein_g: 2, carbs_g: 9, fiber_g: 2, fat_g: 6, sodium_mg: 180 },
        density_g_per_ml: 0.85,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'avial',
        label: 'Avial (Mixed Veg with Coconut)',
        category: 'Vegetable Dishes',
        visual: visuals.AvialVisual,
        nutrients_per_100g: { calories_kcal: 130, protein_g: 3, carbs_g: 14, fiber_g: 5, fat_g: 7, sodium_mg: 220 },
        density_g_per_ml: 0.95,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
    ],
  },
  {
    name: 'Breads & Breakfast',
    items: [
      {
        id: 'roti',
        label: 'Roti / Chapati',
        category: 'Breads & Breakfast',
        visual: visuals.RotiVisual,
        nutrients_per_100g: { calories_kcal: 297, protein_g: 11, carbs_g: 60, fiber_g: 12, fat_g: 2, sodium_mg: 10 },
        portion_g: [30, 60, 90],
        portion_labels: ['1 Roti', '2 Roti', '3 Roti'],
      },
      {
        id: 'paratha',
        label: 'Paratha',
        category: 'Breads & Breakfast',
        visual: visuals.ParathaVisual,
        nutrients_per_100g: { calories_kcal: 320, protein_g: 8, carbs_g: 45, fiber_g: 5, fat_g: 12, sodium_mg: 250 },
        portion_g: [50, 100],
        portion_labels: ['1 Paratha', '2 Parathas'],
        isTreat: true,
      },
      {
        id: 'naan_plain',
        label: 'Plain Naan',
        category: 'Breads & Breakfast',
        visual: visuals.RotiVisual, // Placeholder, can be replaced
        nutrients_per_100g: { calories_kcal: 315, protein_g: 10, carbs_g: 58, fiber_g: 2, fat_g: 5, sodium_mg: 450 },
        portion_g: [80, 160],
        portion_labels: ['1 Naan', '2 Naan'],
        isTreat: true,
      },
      {
        id: 'garlic_naan',
        label: 'Garlic Naan',
        category: 'Breads & Breakfast',
        visual: visuals.GarlicNaanVisual,
        nutrients_per_100g: { calories_kcal: 340, protein_g: 10, carbs_g: 56, fiber_g: 2, fat_g: 9, sodium_mg: 500 },
        portion_g: [90],
        portion_labels: ['1 Naan'],
        isTreat: true,
      },
      {
        id: 'cheese_naan',
        label: 'Cheese Naan',
        category: 'Breads & Breakfast',
        visual: visuals.CheeseNaanVisual,
        nutrients_per_100g: { calories_kcal: 380, protein_g: 14, carbs_g: 54, fiber_g: 2, fat_g: 12, sodium_mg: 600 },
        portion_g: [100],
        portion_labels: ['1 Naan'],
        isTreat: true,
      },
      {
        id: 'poha',
        label: 'Poha',
        category: 'Breads & Breakfast',
        visual: visuals.PohaVisual,
        nutrients_per_100g: { calories_kcal: 150, protein_g: 3, carbs_g: 30, fiber_g: 2, fat_g: 2, sodium_mg: 180 },
        density_g_per_ml: 0.75,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Small', 'Standard', 'Large'],
      },
      {
        id: 'upma',
        label: 'Upma',
        category: 'Breads & Breakfast',
        visual: visuals.UpmaVisual,
        nutrients_per_100g: { calories_kcal: 160, protein_g: 4, carbs_g: 28, fiber_g: 3, fat_g: 3, sodium_mg: 250 },
        density_g_per_ml: 0.8,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Small', 'Standard', 'Large'],
      },
      {
        id: 'masala_dosa',
        label: 'Masala Dosa',
        category: 'Breads & Breakfast',
        visual: visuals.MasalaDosaVisual,
        nutrients_per_100g: { calories_kcal: 168, protein_g: 4, carbs_g: 29, fiber_g: 3, fat_g: 4, sodium_mg: 320 },
        portion_g: [250],
        portion_labels: ['1 Dosa'],
        isTreat: true,
      },
      {
        id: 'tapioca_kappa',
        label: 'Tapioca (Kappa)',
        category: 'Breads & Breakfast',
        visual: visuals.TapiocaKappaVisual,
        nutrients_per_100g: { calories_kcal: 160, protein_g: 0.6, carbs_g: 38, fiber_g: 1.8, fat_g: 0.3, sodium_mg: 14 },
        density_g_per_ml: 0.88,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Small', 'Standard', 'Large'],
      },
      {
        id: 'dosa_plain',
        label: 'Dosa (Plain)',
        category: 'Breads & Breakfast',
        visual: visuals.DosaPlainVisual,
        nutrients_per_100g: { calories_kcal: 155, protein_g: 4, carbs_g: 28, fiber_g: 2, fat_g: 3, sodium_mg: 280 },
        portion_g: [120, 240],
        portion_labels: ['1 Dosa', '2 Dosas'],
      },
      {
        id: 'idli_plain',
        label: 'Idli (Plain)',
        category: 'Breads & Breakfast',
        visual: visuals.IdliPlainVisual,
        nutrients_per_100g: { calories_kcal: 132, protein_g: 4, carbs_g: 25, fiber_g: 2, fat_g: 1, sodium_mg: 240 },
        portion_g: [80, 160, 240],
        portion_labels: ['2 Idlis', '4 Idlis', '6 Idlis'],
      },
    ],
  },
  {
    name: 'Soups, Salads & Sides',
    items: [
      {
        id: 'sambar',
        label: 'Sambar',
        category: 'Soups, Salads & Sides',
        visual: visuals.SambarVisual,
        nutrients_per_100g: { calories_kcal: 85, protein_g: 4, carbs_g: 12, fiber_g: 4, fat_g: 2, sodium_mg: 300 },
        density_g_per_ml: 1.0,
        volume_options_ml: [150, 250],
        volume_labels: ['Side Soup', 'Main Soup'],
      },
      {
        id: 'raita',
        label: 'Cucumber Raita',
        category: 'Soups, Salads & Sides',
        visual: visuals.RaitaVisual,
        nutrients_per_100g: { calories_kcal: 40, protein_g: 3, carbs_g: 4, fiber_g: 1, fat_g: 1.5, sodium_mg: 90 },
        density_g_per_ml: 1.0,
        volume_options_ml: [60, 120],
        volume_labels: ['Garnish', 'Side'],
      },
      {
        id: 'sprouts_salad',
        label: 'Sprouts Salad',
        category: 'Soups, Salads & Sides',
        visual: visuals.SproutsSaladVisual,
        nutrients_per_100g: { calories_kcal: 90, protein_g: 6, carbs_g: 15, fiber_g: 5, fat_g: 1, sodium_mg: 50 },
        density_g_per_ml: 0.8,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'okra_pachadi',
        label: 'Okra Pachadi',
        category: 'Soups, Salads & Sides',
        visual: visuals.OkraPachadiVisual,
        nutrients_per_100g: { calories_kcal: 85, protein_g: 2, carbs_g: 10, fiber_g: 3, fat_g: 4, sodium_mg: 180 },
        density_g_per_ml: 0.90,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'moru_curry_pulissery',
        label: 'Moru Curry (Pulissery)',
        category: 'Soups, Salads & Sides',
        visual: visuals.MoruCurryPulisseryVisual,
        nutrients_per_100g: { calories_kcal: 65, protein_g: 3, carbs_g: 8, fiber_g: 2, fat_g: 2, sodium_mg: 220 },
        density_g_per_ml: 1.0,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
    ],
  },
  {
    name: 'Treats',
    items: [
      {
        id: 'samosa',
        label: 'Samosa',
        category: 'Treats',
        visual: visuals.SamosaVisual,
        nutrients_per_100g: { calories_kcal: 262, protein_g: 4, carbs_g: 24, fiber_g: 2, fat_g: 17, sodium_mg: 400 },
        isTreat: true,
        portion_g: [80, 160],
        portion_labels: ['1 Samosa', '2 Samosas'],
      },
      {
        id: 'laddu',
        label: 'Laddu',
        category: 'Treats',
        visual: visuals.LadduVisual,
        nutrients_per_100g: { calories_kcal: 420, protein_g: 8, carbs_g: 60, fiber_g: 4, fat_g: 18, sodium_mg: 20 },
        isTreat: true,
        portion_g: [30, 60],
        portion_labels: ['1 Laddu', '2 Laddus'],
      },
      {
        id: 'jalebi',
        label: 'Jalebi',
        category: 'Treats',
        visual: visuals.JalebiVisual,
        nutrients_per_100g: { calories_kcal: 380, protein_g: 3, carbs_g: 65, fiber_g: 1, fat_g: 12, sodium_mg: 150 },
        isTreat: true,
        portion_g: [50, 100],
        portion_labels: ['Small Serving', 'Standard Serving'],
      },
      {
        id: 'dal_makhani',
        label: 'Dal Makhani',
        category: 'Treats', // Re-categorized as a rich treat
        visual: visuals.DalMakhaniVisual,
        nutrients_per_100g: { calories_kcal: 180, protein_g: 9, carbs_g: 22, fiber_g: 9, fat_g: 7, sodium_mg: 350 },
        density_g_per_ml: 1.0,
        volume_options_ml: [120, 180],
        volume_labels: ['Side', 'Standard'],
        isTreat: true,
      },
      {
        id: 'butter_chicken',
        label: 'Butter Chicken',
        category: 'Treats', // Re-categorized as a rich treat
        visual: visuals.ButterChickenVisual,
        nutrients_per_100g: { calories_kcal: 220, protein_g: 15, carbs_g: 8, fiber_g: 2, fat_g: 14, sodium_mg: 400 },
        density_g_per_ml: 1.0,
        volume_options_ml: [120, 180],
        volume_labels: ['Side', 'Standard'],
        isTreat: true,
      },
    ]
  }
];

export const DID_YOU_KNOW_TIPS: { id: string, text: string, source_name?: string, source_url?: string }[] = [
  { id: 'fiber', text: "Fiber helps slow down sugar absorption, which is great for stable energy levels." },
  { id: 'protein', text: "Protein is essential for muscle repair, especially after exercise." },
  { id: 'brown_rice', text: "Brown rice retains the bran and germ, giving it more fiber and nutrients than white rice." },
  { id: 'lentils', text: "Lentils (Dal) are a fantastic source of both protein and fiber." },
  { id: 'chillies', text: "The spicy compound in chillies, capsaicin, can have metabolism-boosting effects." },
  { id: 'turmeric', text: "Turmeric, a common spice in Indian cooking, contains curcumin, which has anti-inflammatory properties." },
  { id: 'plate_method', text: "A balanced plate is often described as ½ veggies, ¼ protein, and ¼ complex carbs.", source_name: "ADA", source_url: "https://diabetes.org/food-nutrition/plate-method" },
  { id: 'sodium', text: "Sodium is an essential mineral, but too much can impact blood pressure. Aim for less than 2300mg per day.", source_name: "Dietary Guidelines for Americans", source_url: "https://www.dietaryguidelines.gov/" },
  { id: 'healthy_fats', text: "Healthy fats, like those in avocados and nuts, are vital for brain health." },
  { id: 'whole_wheat', text: "Roti made from whole wheat flour is a great source of complex carbohydrates and fiber." },
];
