// services/nutriserveFoodData.ts
import type { FoodGroup } from '../components/games/NutriServeTypes';
import * as visuals from '../components/games/nutriserve-ui/FoodVisuals';

/**
 * The central data source for all food items available in the NutriServe game.
 * - Nutrients are per 100g.
 * - Density is g/ml, crucial for converting volume to weight.
 * - Portion sizes are in grams.
 * - Volume options are in milliliters.
 */
export const FOOD_LIBRARY: FoodGroup[] = [
  {
    name: 'Grains',
    items: [
      {
        id: 'rice_white',
        label: 'White Rice',
        category: 'Grains',
        visual: visuals.RiceVisual,
        nutrients_per_100g: { calories_kcal: 130, protein_g: 2.7, carbs_g: 28, fiber_g: 0.4, fat_g: 0.3, sodium_mg: 1 },
        density_g_per_ml: 0.85,
        volume_options_ml: [80, 160, 240, 360],
        volume_labels: ['Small Katori', 'Scoop', 'Large Katori', 'Full Plate'],
      },
      {
        id: 'rice_brown',
        label: 'Brown Rice',
        category: 'Grains',
        visual: visuals.BrownRiceVisual,
        nutrients_per_100g: { calories_kcal: 111, protein_g: 2.6, carbs_g: 23, fiber_g: 1.8, fat_g: 0.9, sodium_mg: 5 },
        density_g_per_ml: 0.80,
        volume_options_ml: [80, 160, 240, 360],
        volume_labels: ['Small Katori', 'Scoop', 'Large Katori', 'Full Plate'],
      },
       {
        id: 'rice_red',
        label: 'Red Rice',
        category: 'Grains',
        visual: visuals.RedRiceVisual,
        nutrients_per_100g: { calories_kcal: 120, protein_g: 2.8, carbs_g: 26, fiber_g: 2.0, fat_g: 1.0, sodium_mg: 4 },
        density_g_per_ml: 0.82,
        volume_options_ml: [80, 160, 240],
        volume_labels: ['Small Katori', 'Scoop', 'Large Katori'],
      },
    ],
  },
  {
    name: 'Lentils & Curries',
    items: [
      {
        id: 'chana_masala',
        label: 'Chana Masala',
        category: 'Lentils & Curries',
        visual: visuals.ChanaMasalaVisual,
        nutrients_per_100g: { calories_kcal: 135, protein_g: 7, carbs_g: 18, fiber_g: 7, fat_g: 4, sodium_mg: 250 },
        density_g_per_ml: 0.95,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'palak_dal',
        label: 'Palak Dal',
        category: 'Lentils & Curries',
        visual: visuals.PalakDalVisual,
        nutrients_per_100g: { calories_kcal: 110, protein_g: 6, carbs_g: 14, fiber_g: 5, fat_g: 3, sodium_mg: 200 },
        density_g_per_ml: 0.98,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'masoor_dal',
        label: 'Masoor Dal',
        category: 'Lentils & Curries',
        visual: visuals.MasoorDalVisual,
        nutrients_per_100g: { calories_kcal: 125, protein_g: 8, carbs_g: 19, fiber_g: 8, fat_g: 2, sodium_mg: 180 },
        density_g_per_ml: 0.98,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'moong_dal_tadka',
        label: 'Moong Dal Tadka',
        category: 'Lentils & Curries',
        visual: visuals.MoongDalTadkaVisual,
        nutrients_per_100g: { calories_kcal: 140, protein_g: 9, carbs_g: 17, fiber_g: 7, fat_g: 4, sodium_mg: 220 },
        density_g_per_ml: 0.98,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'rajma_masala',
        label: 'Rajma Masala',
        category: 'Lentils & Curries',
        visual: visuals.RajmaMasalaVisual,
        nutrients_per_100g: { calories_kcal: 145, protein_g: 8, carbs_g: 20, fiber_g: 8, fat_g: 4, sodium_mg: 280 },
        density_g_per_ml: 0.96,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'dal_makhani',
        label: 'Dal Makhani',
        category: 'Lentils & Curries',
        visual: visuals.DalMakhaniVisual,
        nutrients_per_100g: { calories_kcal: 180, protein_g: 9, carbs_g: 22, fiber_g: 9, fat_g: 7, sodium_mg: 350 },
        density_g_per_ml: 1.0,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
        isTreat: true,
      },
      {
        id: 'butter_chicken',
        label: 'Butter Chicken',
        category: 'Lentils & Curries',
        visual: visuals.ButterChickenVisual,
        nutrients_per_100g: { calories_kcal: 220, protein_g: 15, carbs_g: 8, fiber_g: 2, fat_g: 14, sodium_mg: 400 },
        density_g_per_ml: 1.0,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
        isTreat: true,
      },
    ],
  },
  {
    name: 'Vegetable Dishes',
    items: [
       {
        id: 'baingan_bharta',
        label: 'Baingan Bharta',
        category: 'Vegetable Dishes',
        visual: visuals.BainganBhartaVisual,
        nutrients_per_100g: { calories_kcal: 80, protein_g: 2, carbs_g: 9, fiber_g: 4, fat_g: 4, sodium_mg: 150 },
        density_g_per_ml: 0.90,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'bhindi_masala',
        label: 'Bhindi Masala',
        category: 'Vegetable Dishes',
        visual: visuals.BhindiMasalaVisual,
        nutrients_per_100g: { calories_kcal: 95, protein_g: 2, carbs_g: 8, fiber_g: 3, fat_g: 6, sodium_mg: 180 },
        density_g_per_ml: 0.88,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
      {
        id: 'palak_paneer',
        label: 'Palak Paneer',
        category: 'Vegetable Dishes',
        visual: visuals.PalakPaneerVisual,
        nutrients_per_100g: { calories_kcal: 150, protein_g: 9, carbs_g: 7, fiber_g: 3, fat_g: 10, sodium_mg: 300 },
        density_g_per_ml: 0.95,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
       {
        id: 'mixed_veg_curry',
        label: 'Mixed Veg Curry',
        category: 'Vegetable Dishes',
        visual: visuals.MixedVegCurryVisual,
        nutrients_per_100g: { calories_kcal: 90, protein_g: 3, carbs_g: 10, fiber_g: 4, fat_g: 4, sodium_mg: 200 },
        density_g_per_ml: 0.92,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
    ],
  },
  {
    name: 'Breads & Breakfast',
    items: [
      {
        id: 'roti',
        label: 'Roti / Chapati',
        category: 'Breads & Breakfast',
        visual: visuals.RotiVisual,
        nutrients_per_100g: { calories_kcal: 297, protein_g: 11, carbs_g: 60, fiber_g: 12, fat_g: 2, sodium_mg: 10 },
        portion_g: [30, 60, 90],
        portion_labels: ['1 Roti', '2 Roti', '3 Roti'],
      },
       {
        id: 'paratha',
        label: 'Paratha',
        category: 'Breads & Breakfast',
        visual: visuals.ParathaVisual,
        nutrients_per_100g: { calories_kcal: 320, protein_g: 8, carbs_g: 45, fiber_g: 5, fat_g: 12, sodium_mg: 250 },
        portion_g: [50, 100],
        portion_labels: ['1 Paratha', '2 Parathas'],
        isTreat: true,
      },
      {
        id: 'poha',
        label: 'Poha',
        category: 'Breads & Breakfast',
        visual: visuals.PohaVisual,
        nutrients_per_100g: { calories_kcal: 150, protein_g: 3, carbs_g: 30, fiber_g: 2, fat_g: 2, sodium_mg: 180 },
        density_g_per_ml: 0.75,
        volume_options_ml: [120, 180, 240],
        volume_labels: ['Small', 'Standard', 'Large'],
      },
    ],
  },
   {
    name: 'Soups, Salads & Sides',
    items: [
       {
        id: 'sambar',
        label: 'Sambar',
        category: 'Soups, Salads & Sides',
        visual: visuals.SambarVisual,
        nutrients_per_100g: { calories_kcal: 85, protein_g: 4, carbs_g: 12, fiber_g: 4, fat_g: 2, sodium_mg: 300 },
        density_g_per_ml: 1.0,
        volume_options_ml: [150, 250],
        volume_labels: ['Side Soup', 'Main Soup'],
      },
       {
        id: 'raita',
        label: 'Cucumber Raita',
        category: 'Soups, Salads & Sides',
        visual: visuals.RaitaVisual,
        nutrients_per_100g: { calories_kcal: 40, protein_g: 3, carbs_g: 4, fiber_g: 1, fat_g: 1.5, sodium_mg: 90 },
        density_g_per_ml: 1.0,
        volume_options_ml: [60, 120],
        volume_labels: ['Garnish', 'Side'],
      },
      {
        id: 'sprouts_salad',
        label: 'Sprouts Salad',
        category: 'Soups, Salads & Sides',
        visual: visuals.SproutsSaladVisual,
        nutrients_per_100g: { calories_kcal: 90, protein_g: 6, carbs_g: 15, fiber_g: 5, fat_g: 1, sodium_mg: 50 },
        density_g_per_ml: 0.8,
        volume_options_ml: [100, 150, 200],
        volume_labels: ['Side', 'Standard', 'Large'],
      },
    ],
  },
  {
    name: 'Treats',
    items: [
      {
        id: 'samosa',
        label: 'Samosa',
        category: 'Treats',
        visual: visuals.SamosaVisual,
        nutrients_per_100g: { calories_kcal: 262, protein_g: 4, carbs_g: 24, fiber_g: 2, fat_g: 17, sodium_mg: 400 },
        isTreat: true,
        portion_g: [80, 160],
        portion_labels: ['1 Samosa', '2 Samosas'],
      },
       {
        id: 'laddu',
        label: 'Laddu',
        category: 'Treats',
        visual: visuals.LadduVisual,
        nutrients_per_100g: { calories_kcal: 420, protein_g: 8, carbs_g: 60, fiber_g: 4, fat_g: 18, sodium_mg: 20 },
        isTreat: true,
        portion_g: [30, 60],
        portion_labels: ['1 Laddu', '2 Laddus'],
      },
       {
        id: 'jalebi',
        label: 'Jalebi',
        category: 'Treats',
        visual: visuals.JalebiVisual,
        nutrients_per_100g: { calories_kcal: 380, protein_g: 3, carbs_g: 65, fiber_g: 1, fat_g: 12, sodium_mg: 150 },
        isTreat: true,
        portion_g: [50, 100],
        portion_labels: ['Small Serving', 'Standard Serving'],
      },
    ]
  }
];
