/**
 * Static mapping of recipe IDs to their actual image filenames in public/dataset/food-images/
 * This mapping ensures consistent image loading across the application.
 *
 * The dataset uses inconsistent naming conventions:
 * - Some files use Title_Case with underscores
 * - Some use lowercase_with_underscores
 * - Some use hyphens for special chars (Carrot-Payasam)
 * - Some use double underscores for parentheses (Avial__Mixed_Vegetable_Curry_)
 *
 * This map provides the definitive source of truth for recipe-to-image mapping.
 * Generated by analyzing actual files in public/dataset/food-images/
 */
export const RECIPE_IMAGE_FILENAME_MAP: Record<string, string> = {
    // Kerala Traditional Dishes (using display name format)
    'rcp_ada_pradhaman': 'Ada_Pradhaman',
    'rcp_palada_pradhaman': 'Palada_Pradhaman',
    'rcp_wheat_rava_payasam': 'Wheat_Rava_Payasam',
    'rcp_carrot_payasam': 'Carrot-Payasam',
    'rcp_avial': 'Avial__Mixed_Vegetable_Curry_',
    'rcp_olan': 'Olan__Ash_Gourd___Cowpea_Stew_',
    'rcp_kalan': 'Kalan__Yam___Plantain_Yogurt_Curry_',
    'rcp_kootu_curry': 'kootu_curry__black_chickpeas__plantain___yam_',
    'rcp_pulissery': 'Pulissery__Buttermilk_Curry_',
    'rcp_moru_curry': 'moru_curry__pulissery_',
    'rcp_vegetable_stew': 'kerala_vegetable_stew__ishtu_',
    'rcp_potato_stew': 'kerala_potato_stew',
    'rcp_rasam': 'kerala_rasam__spiced_soup_',
    'rcp_parippu_curry': 'Kerala_Parippu_Curry__Moong_Dal_',
    'rcp_sambar': 'sambar',
    'rcp_kerala_sambar': 'Kerala_Sambar__Vegetable_Lentil_Stew_',
    'rcp_vegetable_kurma': 'Kerala_Vegetable_Kurma',
    'rcp_kadala_curry': 'Kadala_Curry__Brown_Chickpea_Curry_',
    'rcp_mathi_curry': 'mathi_kerala_sardine_curry',
    'rcp_kerala_beef_curry': 'keralan_beef_curry',
    'rcp_kerala_lamb_curry': 'keralan_lamb_curry',

    // Kerala Thoran (Stir Fry) Dishes
    'rcp_cabbage_thoran': 'Cabbage_Thoran',
    'rcp_beetroot_thoran': 'Beetroot_Thoran',
    'rcp_beans_carrot_thoran': 'Beans___Carrot_Thoran',
    'rcp_spinach_thoran': 'Spinach_Thoran__Cheera_Thoran_',
    'rcp_moringa_thoran': 'Moringa_Leaf_Thoran__Drumstick_Leaves_',
    'rcp_banana_stem_thoran': 'Banana_Stem_Thoran',
    'rcp_banana_flower_thoran': 'Banana_Flower_Thoran',
    'rcp_mushroom_thoran': 'Mushroom_Thoran',
    'rcp_mixed_vegetable_thoran': 'Mixed_Vegetable_Thoran',
    'rcp_mixed_sprouts_thoran': 'Mixed_Sprouts_Thoran',
    'rcp_spinach_dal_thoran': 'Spinach_Dal_Thoran_Cheera_Parippu',
    'rcp_jackfruit_seeds_thoran': 'Jackfruit_Seeds_Thoran__Chakkakuru_Thoran_',
    'rcp_pumpkin_beans_thoran': 'Pumpkin-_-Beans-Thoran',

    // Kerala Pachadi (Yogurt Side Dishes)
    'rcp_cucumber_pachadi': 'Cucumber_Pachadi__Vellarikka_Kichadi_',
    'rcp_mango_pachadi': 'Mango_Pachadi',
    'rcp_pineapple_pachadi': 'Pineapple_Pachadi',
    'rcp_okra_pachadi': 'Okra_Pachadi',

    // Kerala Other Dishes
    'rcp_pumpkin_erissery': 'Pumpkin_Erissery__Mathanga_Erissery_',
    'rcp_bottle_gourd_kootu': 'Bottle_Gourd_Kootu',
    'rcp_malabar_spinach_curry': 'Malabar_Spinach_Curry__Basella_Stew_',
    'rcp_tomato_chutney': 'Tomato_Chutney__Thakkali_Chammanthi_',
    'rcp_mashed_tapioca': 'Mashed_Tapioca__Kappa_Vevichathu_',
    'rcp_tapioca_green_gram': 'tapioca_with_green_gram__kappa___payar_',
    'rcp_yam_stir_fry': 'Yam-Stir-Fry-_Chena-Mezhukkupuratti_',
    'rcp_chinese_potato_stir_fry': 'Chinese-Potato-Stir-Fry-_Koorka-Mezhukkupuratti_',

    // Kerala Breakfast Items
    'rcp_appam': 'appam__rice_hoppers_',
    'rcp_idiyappam': 'idiyappam__rice_string_hoppers_',
    'rcp_puttu': 'puttu__steamed_rice___coconut_',
    'rcp_ragi_puttu': 'ragi_puttu__finger_millet_steamed_cake_',
    'rcp_idli_kerala': 'kerala_idli__steamed_rice_cakes_',
    'rcp_brown_rice_kanji': 'Brown_Rice_Kanji__Rice_Porridge_',
    'rcp_oats_upma': 'oats_upma__kerala_style_',

    // North Indian Dishes (using ID format - lowercase)
    'rcp_chana_masala': 'chana_masala',
    'rcp_palak_dal': 'palak_dal',
    'rcp_masoor_dal': 'masoor_dal',
    'rcp_moong_dal_tadka': 'moong_dal_tadka',
    'rcp_bhindi_masala': 'bhindi_masala',
    'rcp_baingan_bharta': 'baingan_bharta',
    'rcp_rajma_masala': 'rajma_masala',
    'rcp_lemon_rice': 'lemon_rice',
    'rcp_dosa_plain': 'dosa',
    'rcp_idli_plain': 'idili',

    // Beverages
    'rcp_masala_chai_low_sugar': 'Masala_Chai__Low_Sugar_',
    'rcp_turmeric_milk': 'Golden_Milk__Turmeric_Latte_',

    // Snacks & Sides
    'rcp_bruschetta': 'Tomato___Basil_Bruschetta',
    'rcp_coconut_chutney': 'Coconut_Chutney__Thenga_Chammanthi_',

    // Green Gram Curry (same as Kerala Parippu - Moong Dal)
    'rcp_green_gram_curry': 'Kerala_Parippu_Curry__Moong_Dal_',

    // Special case - fallbacks for recipes without exact matches
    // These will fallback to emoji if image not found
};

/**
 * Static mapping of NutriServe food IDs to their actual image filenames.
 * NutriServe uses different IDs than recipes (e.g., "mathi_sardine_curry" vs "rcp_mathi_curry").
 */
export const NUTRISERVE_FOOD_IMAGE_MAP: Record<string, string> = {
    // NutriServe-specific mappings
    'moringa_leaf_thoran': 'Moringa_Leaf_Thoran__Drumstick_Leaves_',
    'okra_pachadi': 'Okra_Pachadi',
    'dosa_plain': 'dosa',
    'mathi_sardine_curry': 'mathi_kerala_sardine_curry',
    'beans_carrot_thoran': 'Beans___Carrot_Thoran',
    'kerala_lamb_curry': 'keralan_lamb_curry',
    'kerala_beef_curry': 'keralan_beef_curry',
    'moru_curry_pulissery': 'moru_curry__pulissery_',
    'kerala_parippu_curry': 'Kerala_Parippu_Curry__Moong_Dal_',
    'rice_brown': 'rice_brown',

    // Other NutriServe foods that match recipe IDs (without rcp_ prefix)
    'chana_masala': 'chana_masala',
    'palak_dal': 'palak_dal',
    'lemon_rice': 'lemon_rice',
    'masala_dosa': 'masala_dosa',
    'idli_plain': 'idili',
    'kerala_sambar': 'Kerala_Sambar__Vegetable_Lentil_Stew_',
    'kadala_curry': 'Kadala_Curry__Brown_Chickpea_Curry_',
    'banana_flower_thoran': 'Banana_Flower_Thoran',
    'jackfruit_seeds_thoran': 'Jackfruit_Seeds_Thoran__Chakkakuru_Thoran_',
    'malabar_spinach_curry': 'Malabar_Spinach_Curry__Basella_Stew_',
    'bottle_gourd_kootu': 'Bottle_Gourd_Kootu',
    'mashed_tapioca': 'Mashed_Tapioca__Kappa_Vevichathu_',
};

/**
 * Gets the actual filename for a recipe's image from the mapping.
 * Returns null if no mapping exists (will fallback to emoji).
 *
 * @param recipeId - The recipe ID (e.g., "rcp_chana_masala")
 * @returns The actual filename without extension, or null if not mapped
 */
export function getRecipeImageFilename(recipeId: string): string | null {
    return RECIPE_IMAGE_FILENAME_MAP[recipeId] || null;
}

/**
 * Gets the actual filename for a NutriServe food image from the mapping.
 * Returns null if no mapping exists.
 *
 * @param foodId - The food ID (e.g., "mathi_sardine_curry")
 * @returns The actual filename without extension, or null if not mapped
 */
export function getNutriServeFoodImageFilename(foodId: string): string | null {
    return NUTRISERVE_FOOD_IMAGE_MAP[foodId] || null;
}
