import React from 'react';
import type { Recipe } from '../types';
import { FireIcon, HeartIcon } from './icons/Icons';

interface RecipeCardProps {
  recipe: Recipe;
  onClick: () => void;
}

const RecipeCard: React.FC<RecipeCardProps> = ({ recipe, onClick }) => {
  return (
    <div
      className="bg-white rounded-xl shadow-md overflow-hidden cursor-pointer group transition-all duration-300 hover:shadow-xl hover:-translate-y-1"
      onClick={onClick}
    >
      <div className="relative">
        {recipe.image && (recipe.image.startsWith('http') ? 
          <img className="h-40 w-full object-cover" src={recipe.image} alt={recipe.name} /> : 
          <div className="h-40 w-full flex items-center justify-center bg-green-50 text-4xl">{recipe.image}</div>
        )}
        <div className="absolute top-0 right-0 p-2 bg-black/40 rounded-bl-xl">
            {recipe.source === 'gemini' && <span title="Generated by AI" className="text-xl">✨</span>}
            {recipe.source === 'user' && <span title="Your Recipe" className="text-xl">👤</span>}
            {recipe.source === 'preloaded' && <span title="Vibe Recipe" className="text-xl">🌿</span>}
        </div>
      </div>
      <div className="p-4">
        <h3 className="font-bold text-lg text-green-900 truncate group-hover:text-green-600 transition-colors">{recipe.name}</h3>
        <p className="text-sm text-gray-500 capitalize">{recipe.course}</p>
        <div className="flex items-center justify-between mt-3 text-sm text-gray-600">
            <div className="flex items-center">
                <FireIcon className={`h-4 w-4 ${recipe.spice_level > 0 ? 'text-red-500' : 'text-gray-400'}`} />
                <span className="ml-1">{['Mild', 'Spicy', 'Hot', 'Fiery'][recipe.spice_level]}</span>
            </div>
            {recipe.diabetic_friendly && (
                 <div className="flex items-center" title="Diabetic Friendly">
                    <HeartIcon className="h-4 w-4 text-blue-500" />
                    <span className="ml-1">DF</span>
                </div>
            )}
        </div>
      </div>
    </div>
  );
};

export default RecipeCard;
